core-ds/core-components

- packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap
- packages/filter-tag/src/Component.tsx
- packages/filter-tag/src/__snapshots__/Component.test.tsx.snap
- packages/filter-tag/src/index.module.css
- packages/link/src/Component.test.tsx
- packages/link/src/Component.tsx
- packages/link/src/default.module.css
- packages/link/src/inverted.module.css
- packages/pagination/src/Component.tsx
- packages/pagination/src/index.module.css
- packages/radio-group/src/__snapshots__/Component.test.tsx.snap
- packages/select-with-tags/src/__snapshots__/component.test.tsx.snap
- packages/tabs/src/components/tabs/__snapshots__/Component.test.tsx.snap
- packages/tag/src/Component.tsx
- packages/tag/src/__snapshots__/Component.test.tsx.snap
- packages/tag/src/index.module.css
> fix(*): default className bug

- packages/form-control/src/index.module.css
- packages/vars/src/typography.css
Изменила текстовые стили и позиционирование Label
> fix(form-control): fix label line-height

- packages/form-control/src/index.module.css
- packages/vars/src/typography.css
исправить высоту линии метки (#14)"
Reverts commit b430f890dd682ac21ac24c4d6ebde31a941789a1.
> fix(form-control): revert - исправить высоту линии метки

- packages/toast/src/index.module.css
[Ticket](http://jira.moscow.alfaintra.net/browse/NEWCLICKUI-604)
Обнаружили, что в тосте могут выводиться длинные названия продуктов (например), которые вводит клиент, и получаются некрасивые моменты, как тут https://prnt.sc/CtLKqK9aVRwE
> feat(NEWCLICKUI-604): Break text in toast

- packages/confirmation/src/component.tsx
fix #3 
При переходе в TEMP_BLOCK — таймер не будет останавливаться
```
render(() => {
const { 
confirmationState,
confirmationScreen,
setConfirmationState,
setConfirmationScreen,
} = useConfirmation();
const attemps = React.useRef(0);
const handleInputFinished = code => {
setConfirmationScreen("INITIAL");
setConfirmationState("CODE_SENDING");
setTimeout(() => {
setConfirmationState('CODE_ERROR');
}, 1000);
};
const handleSmsRetryClick = () => {
attemps.current++;
setTimeout(() => {
setConfirmationState("INITIAL");
if (attemps.current === 1) {
setConfirmationScreen('TEMP_BLOCK')
}
}, 1000);
};
return (
<Space direction='vertical'>
<Confirmation
screen={confirmationScreen}
state={confirmationState}
onChangeState={setConfirmationState}
onChangeScreen={setConfirmationScreen} …
```
> fix(confirmation): fix countdown timer

- packages/code-input/src/components/input/index.module.css
инпуты становятся жёлтыми (см. скрин) → надо убрать дефолтный стиль.
> fix(code-input): auto-fill styles

- jest.config.js
- packages/button/src/Component.test.tsx
- packages/button/src/Component.tsx
- packages/button/src/index.module.css
Добавляю обрезание текста в кнопке при свойстве nowrap
> feat(button): add overflow hidden and text overflow ellipsis for nowrap

- packages/file-upload-item/src/Component.tsx
change condition about icon and error view
> refactor(file-upload-item)

- packages/toast/src/__snapshots__/component.test.tsx.snap
- packages/toast/src/component.test.tsx
- packages/toast/src/component.tsx
Добавляю возможность отображения по ширине родителя для тоста
> feat(toast): add use anchor width for popover

- packages/modal/src/Component.desktop.tsx
У Modal перезатирается проп invisible, передаваемый в backdropProps
[пример с backdropProps](https://core-ds.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=%2F%2F%20import%20%7B%20Typography%20%7D%20from%20%27%40alfalab%2Fcore-components%2Ftypography%27%3B%0Arender(()%20%3D%3E%20%7B%0A%20%20const%20%5Bopen%2C%20setOpen%5D%20%3D%20React.useState(false)%3B%0A%20%20const%20handleModalOpen%20%3D%20()%20%3D%3E%20setOpen(!open)%3B%0A%20%20return%20(%0A%20%20%20%20%3CReact.Fragment%3E%0A%20%20%20%20%20%20%3CButton%20type%3D%22button%22%20size%3D%22xs%22%20onClick%3D%7BhandleModalOpen%7D%3E%0A%20%20%20%20%20%20%20%20%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%20%D0%BC%D0%BE%D …
> fix(modal): rewrite invisible prop from backdropProps

- packages/chart/src/docs/Component.stories.mdx
Восстановлено превью компонента chart в storybook
> fix(chart): chart stories restored

- packages/calendar-range/src/Component.tsx
- packages/calendar-range/src/docs/Component.stories.mdx
- packages/calendar-range/src/hooks.ts
- packages/calendar-range/src/views/static.tsx
Пропса для отображения дефолтного месяца в правой части компонента
> feat(calendar-range): default month position

- packages/table/src/components/pagination/Component.tsx
Пофиксил пропажу постранички в таблицах
> fix(table): pagination_disappearance

- packages/bottom-sheet/src/__snapshots__/component.test.tsx.snap
- packages/calendar-input/src/__snapshots__/Component.test.tsx.snap
- packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
- packages/date-input/src/Component.tsx
- packages/date-input/src/__snapshots__/Component.test.tsx.snap
> feat(date-input): removed date validation

- package.json
- packages/amount-input/package.json
- packages/amount/package.json
- packages/attach/package.json
- packages/confirmation/package.json
- packages/filter-tag/package.json
- packages/intl-phone-input/package.json
- yarn.lock
Обновляем версии utils и data для добавления металлических валют
> chore: up alfalab/data and utils to add new currencies

- packages/badge/src/docs/description.mdx
- packages/badge/src/index.module.css
Добавила box-sizing: border-box для обертки бейджа
> fix(badge): fix box-sizing

- packages/badge/src/Component.test.tsx
- packages/badge/src/Component.tsx
- packages/notification/src/__snapshots__/Component.test.tsx.snap
- packages/toast-plate/src/__snapshots__/component.test.tsx.snap
Перенесла className на обертку , обновила тесты
> fix(badge): fix classname

- packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
- packages/calendar/src/__snapshots__/Component.test.tsx.snap
- packages/file-upload-item/src/__snapshots__/Component.test.tsx.snap
- packages/icon-button/src/Component.tsx
- packages/icon-button/src/__snapshots__/Component.test.tsx.snap
- packages/notification-manager/src/__snapshots__/component.test.tsx.snap
- packages/notification/src/__snapshots__/Component.test.tsx.snap
- packages/password-input/src/__snapshots__/component.test.tsx.snap
Пофиксила состояние загрузки(бы сдвиг вправо)
> fix(icon-button): fix loading

- packages/bottom-sheet/src/__snapshots__/component.test.tsx.snap
- packages/bottom-sheet/src/component.tsx
- packages/bottom-sheet/src/components/header/Component.tsx
- packages/bottom-sheet/src/components/header/index.module.css
- packages/input-autocomplete/package.json
- packages/input-autocomplete/src/Component.mobile.tsx
- packages/input-autocomplete/src/Component.test.tsx
- packages/input-autocomplete/src/__image_snapshots__/input-autocomplete-mobile-interactions-tests-fill-value-2-snap.png
- packages/input-autocomplete/src/__image_snapshots__/input-autocomplete-mobile-interactions-tests-fill-value-3-snap.png
- packages/input-autocomplete/src/__image_snapshots__/input-autocomplete-mobile-interactions-tests-fill-value-snap.png
- packages/input-autocomplete/src/__snapshots__/Component.test.tsx.snap
- packages/input-autocomplete/src/autocomplete-mobile-field/Component.tsx
- packages/input-autocomplete/src/autocomplete-mobile-field/index.module.css
- packages/input-autocomplete/src/autocomplete-mobile-field/index.ts
- packages/input-autocomplete/src/component.screenshots.test.tsx
- packages/input-autocomplete/src/docs/Component.stories.mdx
- packages/input-autocomplete/src/docs/description.mdx
- packages/input-autocomplete/src/mobile.module.css
- packages/input-autocomplete/src/mobile.ts
- packages/input-autocomplete/tsconfig.json
- packages/select/src/components/select-mobile/Component.tsx
Новый компонент InputAutocompleteMobile
> feat(input-autocomplete): add new component InputAutocompleteMobile

- packages/input-autocomplete/src/Component.mobile.tsx
- packages/select/src/typings.ts
Исправил ошибку в типе onChange у компонента InputAutocompleteMobile
> fix(input-autocomplete): fixed onChange type

- packages/tooltip/src/component.responsive.tsx
Добавил св-во bottomSheetProps в TooltipResponsive компонент для передачи пропсов BottomSheet
> feat(tooltip): add bottomSheetProps for TooltipResponsive

- package.json
- packages/file-upload-item/src/__image_snapshots__/file-upload-item-hide-meta-when-upload-status-success-name-0-upload-date-0-size-0-show-delete-0-upload-status-1-snap.png
- packages/file-upload-item/src/__image_snapshots__/file-upload-item-hide-meta-when-upload-status-success-name-0-upload-date-0-size-0-show-delete-0-upload-status-2-snap.png
- packages/file-upload-item/src/__image_snapshots__/file-upload-item-name-with-statuses-name-0-upload-status-2-show-delete-0-snap.png
- packages/file-upload-item/src/__image_snapshots__/file-upload-item-name-with-statuses-name-0-upload-status-3-show-delete-0-snap.png
- packages/file-upload-item/src/component.screenshots.test.tsx
- packages/spinner/package.json
- packages/spinner/src/Component.test.tsx
- packages/spinner/src/Component.tsx
- packages/spinner/src/__snapshots__/Component.test.tsx.snap
- packages/spinner/src/docs/Component.stories.mdx
- packages/spinner/src/docs/description.mdx
- packages/spinner/src/index.module.css
- yarn.lock
- Spinner заменен на векторный.
- Добавлена inverted тема.
- Добавлен xs размер.
> feat(spinner): new size & inverted theme

- packages/bottom-sheet/src/component.tsx
Нет возможности установить кастомный класс на модальное окно
Есть возможности установить кастомный класс на модальное окно
Добавил возможность установить кастоный класс на модальное окно
> feat(bottom-sheet): add prop to set modal classname

- packages/base-modal/src/Component.tsx
Исправил использование ResizeObserver'a
> fix(base-modal): fix using resize observer

- packages/base-modal/src/Component.tsx
Проблема была связана с тем, что если не дожидаясь завершения анимации закрытия открыть модалку снова, то повторно вызывалась функция handleContainer, которая внутри считала, что открылось уже второе модальное окно, хотя открывалась эта же самая модалка. А удаление стилей с контейнера происходит при закрытии последнего модального окна.
Сейчас функция handleContainer повторно будет вызываться только тогда, когда анимация закрытия была завершена и стили с body были уже убраны(флаг exited === true), либо на первый рендер(exited === null)
> fix(base-modal): fix overflow hidden bug

- packages/pure-cell/src/__image_snapshots__/pure-cell-screenshots-direction-horizontal-direction-0-snap.png
- packages/pure-cell/src/components/content/index.module.css
- packages/pure-cell/src/docs/description.mdx
> fix(pure-cell): fix content

- jest.screenshots.config.js
- packages/screenshot-utils/setupScreenshotTesting.ts
Очень часто падают тесты с ошибкой истечения таймаута, поднял время до 200000мс
> fix: timeout time up

- packages/tabs/src/components/primary-tablist/Component.tsx
- packages/tabs/src/components/secondary-tablist/Component.tsx
- packages/tabs/src/components/tabs/Component.tsx
- packages/tabs/src/typings.ts
При использовании табов отсутствует возможность добавить класс кнопке таба, пропс className относится к контейнеру для children.
> feat(tabs): added className for tab button and tab`s children

- packages/tooltip/src/Component.tsx
Добавил пропсу для тултипа, чтобы ширина определялась передаваемым anchor элементом
> feat(tooltip): add use anchor width for popover

- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-full-header-full-height-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-full-header-small-height-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-interactions-tests-open-sheet-2-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-interactions-tests-open-sheet-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-left-title-with-closer-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-no-header-no-footer-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-no-title-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-title-align-left-snap.png
- packages/bottom-sheet/src/index.module.css
- packages/vars/src/border-radius.css
Изменила скругление сверху у шторки с 16 на 24рх
> fix(bottom-sheet): fix component border-radius

- packages/modal/src/Component.responsive.tsx
Добавил props для возможности динамически изменять вид компонента.
> feat(modal): add props breakpoint for modal responsive

- packages/themes/src/mixins/mobile.ts
Добавил js файл для стилей мобайля, что бы можно было динамически их подцеплять как темную тему.
> feat(themes): Added the ability to connect styleMobile via js file

- packages/progress-bar/src/Component.test.tsx
- packages/progress-bar/src/Component.tsx
- packages/progress-bar/src/__image_snapshots__/progress-bar-main-props-sprite-snap.png
- packages/progress-bar/src/__snapshots__/Component.test.tsx.snap
- packages/progress-bar/src/index.module.css
Пофиксил баг, проявлялся когда значение value превышало 100
> fix(progress-bar): mechanics of progress line fixed

- packages/bottom-sheet/src/component.tsx
- packages/bottom-sheet/src/components/backer/Component.tsx
- packages/bottom-sheet/src/components/closer/Component.tsx
- packages/bottom-sheet/src/components/header/Component.tsx
- packages/bottom-sheet/tsconfig.json
- packages/modal/src/components/closer/Component.tsx
- packages/modal/src/components/header/Component.desktop.tsx
- packages/modal/src/components/header/Component.mobile.tsx
- packages/modal/src/components/header/Component.tsx
- packages/modal/tsconfig.json
Не хватает тестовых локаторов для элементов компонентов BottomSheet и Modal.
У элементов компонентов BottomSheet и Modal (таких как кнопки закрытия, кнопки "Назад", заголовка и т.д.) есть атрибут data-test-id.
> feat(bottom-sheet, modal): добавлены dataTestId для элементов компонентов

- packages/picker-button/src/Component.tsx
- packages/picker-button/src/__snapshots__/Component.test.tsx.snap
- packages/picker-button/src/component.screenshots.test.tsx
- packages/picker-button/src/index.module.css
Проблема аналогичная с https://github.com/core-ds/core-components/pull/103
> fix(picker-button): increased css specificity

- packages/link/src/Component.test.tsx
- packages/link/src/Component.tsx
- packages/link/src/__image_snapshots__/link-addons-left-addons-0-right-addons-0-snap.png
- packages/link/src/__image_snapshots__/link-addons-left-addons-1-right-addons-0-snap.png
- packages/link/src/__image_snapshots__/link-pseudo-sprite-snap.png
- packages/link/src/__image_snapshots__/link-pseudo-underline-sprite-snap.png
- packages/link/src/component.screenshots.test.tsx
- packages/link/src/docs/Component.stories.mdx
- packages/link/src/docs/description.mdx
- packages/link/src/index.module.css
> feat(link): implemented new view & updated styles

- packages/pure-cell/src/components/addon/index.module.css
- packages/pure-cell/src/components/category/index.module.css
- packages/pure-cell/src/docs/description.mdx
Пофиксила подкомпоненты  аддон и категория
> fix(pure-cell): fix subcomponent addon and category

- packages/table/src/components/table-context/index.tsx
- packages/table/src/components/table/Component.tsx
- packages/table/src/components/tcell/Component.tsx
- packages/table/src/components/tcell/index.module.css
- packages/table/src/components/thead-cell/Component.tsx
- packages/table/src/components/thead-cell/index.module.css
- packages/table/src/components/thead/index.module.css
- packages/table/src/docs/Component.stories.mdx
- packages/table/src/docs/description.mdx
Изменение отступов у компонентов таблицы, добавление пропа для компактных горизонтальных отступов.
> feat(table): change paddings, new compactHorizontal prop

- packages/amount/package.json
- packages/amount/src/__snapshots__/component.test.tsx.snap
- packages/amount/src/component.test.tsx
- packages/amount/src/component.tsx
- yarn.lock
В компонент [Amount](https://core-ds.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-amount--amount) может приходить currency, которого нет в [справочнике](https://git.moscow.alfaintra.net/projects/EF/repos/utils/browse/packages/data/src/currency/data.ts), вследствие чего отображается `undefined` ([песочница](https://core-ds.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=%2F%2F%20import%20%7B%20Typography%20%7D%20from%20%27%40alfalab%2Fcore-components%2Ftypography%27%3B%0A%0A%3CTypography.Title%20font%3D%27system%27%3E%0A%20%20%20%20%3CAmount%20value%3D%7B100000000%7D%20minority%3D%7B100%7D%20currency%3D%22TNT …
> fix(amount): fix undefined symbol

- packages/pure-cell/src/component.tsx
> fix(pure-cell): fix link

- packages/toast/src/index.module.css
Closes #219
[Related task](https://jira.moscow.alfaintra.net/browse/NEWCLICK1-3501)
> fix(toast): Word breaking rule

- packages/select/src/Component.test.tsx
- packages/select/src/components/option/Component.tsx
- packages/select/src/typings.ts
Добавляю в Select OptionShape возможность не рендерить Checkmark
> feat(select): add show check mark to option shape

- packages/skeleton/src/Component.tsx
При выставление класса на скелетон если свойство visible класс отсутствует у контейнера
Класс будет проставлен
> fix(skeleton): added className for visible === false

- packages/input-autocomplete/src/Component.mobile.tsx
- packages/input-autocomplete/src/docs/description.mdx
Добавила возможность прокидывать кастомный инпут
> fix(input-autocomplete): add props custom input

- packages/pure-cell/src/components/text/component.tsx
Добавила возможность прокидывать в слот value компонент
> fix(pure-cell): fix pure-cell text

- packages/notification-manager/src/__snapshots__/component.test.tsx.snap
- packages/notification/src/__snapshots__/Component.test.tsx.snap
- packages/notification/src/docs/Component.stories.mdx
- packages/themes/src/dark.css
- packages/toast-plate/src/__image_snapshots__/click-toast-plate-action-button-2-snap.png
- packages/toast-plate/src/__image_snapshots__/click-toast-plate-inverted-views-2-snap.png
- packages/toast-plate/src/__image_snapshots__/default-toast-plate-action-button-snap.png
- packages/toast-plate/src/__image_snapshots__/default-toast-plate-inverted-views-snap.png
- packages/toast-plate/src/__snapshots__/component.test.tsx.snap
- packages/toast-plate/src/component.screenshots.test.tsx
- packages/toast-plate/src/component.tsx
- packages/toast-plate/src/default.module.css
- packages/toast-plate/src/docs/Component.stories.mdx
- packages/toast-plate/src/index.module.css
- packages/toast-plate/src/inverted.module.css
- packages/toast-plate/src/vars.css
- packages/toast/src/__snapshots__/component.test.tsx.snap
- packages/toast/src/docs/component.stories.mdx
Добавила inverted тему для сомпонентов toast-plate, toast и notification
обновила стори и тесты
> feat(toast-plate): added inverted views

- packages/tabs/src/components/primary-tablist/mobile.module.css
- packages/tabs/src/vars.css
- packages/themes/src/mixins/tabs/click.css
Обновила шрифт и сопутствующие свойства у мобильных табов в теме клика 
И убрала верхний отступ у мобильных табов
> feat(tabs): update theme click

- packages/plate/src/index.module.css
В проекте нужно заюзать кастомный box-shadow для Plate'а
Можно изменять box-shadow с помощью переменной
> feat(plate): added custom variable for box-shadow

- .github/workflows/update-screenshots.yml
Workflow dispatch для обновления скриншотов. После его окончания бот делает коммит с обновленными скриншотами
> chore: creating screenshot update workflow

- .changeset/short-brooms-brush.md
- packages/confirmation-v1/package.json
- packages/confirmation-v1/src/index.ts
- yarn.lock
- Добавил реэкспорт для компонента и типа пропсов как Confirmation & ConfirmationProps
> feat(confirmation-v1): add re-export as Confirmation

- packages/collapse/src/docs/Component.stories.mdx
> docs(collapse): fix import in docs

- .changeset/fast-shrimps-prove.md
- packages/collapse/src/Component.tsx
> fix(collapse): remove unused style prop

- .changeset/lazy-dogs-care.md
- .changeset/witty-sloths-search.md
- package.json
- packages/amount-input/package.json
- packages/amount/package.json
- packages/attach/package.json
- packages/confirmation-v1/package.json
- packages/confirmation/package.json
- packages/filter-tag/package.json
- packages/intl-phone-input/package.json
- yarn.lock
Поднял  до последних версий @alfalab/data & @alfalab/utils
> chore: поднял @alfalab/data & @alfalab/utils версии

- .changeset/neat-fans-search.md
- packages/badge/src/__image_snapshots__/badge-screenshots-view-count-sprite-snap.png
- packages/badge/src/index.module.css
- packages/tabs/src/components/primary-tablist/index.module.css
- packages/tabs/src/vars.css
- packages/themes/src/mixins/tabs/click.css
уменьшила font-size до 11px для размера s (высота 16-17) в компоненте badge 
компоненте tabs свойство  font-feature-settings: 'ss01' назначила только для темы клик
> fix(badge): fix font badge and tabs

- CHANGELOG.md
- docs/6.typography.stories.mdx
- packages/vars/CHANGELOG.md
Дополнил ченджлоги про изменения в последней мажорке и гайд по типографике
> docs: updated changelogs and typography guide

- .changeset/sharp-forks-bow.md
- packages/slider/src/index.module.css
- packages/slider/src/vars.css
https://jira.moscow.alfaintra.net/browse/PDS-587
> fix(slider): increase clickable area

- .changeset/gentle-schools-watch.md
- packages/base-modal/src/Component.test.tsx
- packages/base-modal/src/Component.tsx
- packages/portal/src/Component.tsx
- packages/portal/src/docs/description.mdx
Исправлена проблема с доступом к ref-ам контента, который рендерился через portal.
> fix(portal): fixed missing ref

- .changeset/young-panthers-sing.md
- package.json
- packages/amount-input/package.json
- packages/amount-input/src/Component.test.tsx
- packages/amount-input/src/__snapshots__/Component.test.tsx.snap
- packages/amount/package.json
- packages/amount/src/__image_snapshots__/amount-screenshots-main-snap.png
- packages/amount/src/component.test.tsx
- packages/amount/src/component.tsx
- packages/amount/src/docs/component.stories.mdx
- packages/amount/src/docs/description.mdx
- packages/amount/src/types/amount-props.ts
- packages/attach/package.json
- packages/confirmation-v1/package.json
- packages/confirmation/package.json
- packages/filter-tag/package.json
- packages/intl-phone-input/package.json
- packages/pure-cell/src/__image_snapshots__/pure-cell-screenshots-direction-horizontal-direction-0-snap.png
- yarn.lock
Добавлен новый пропс codeFormat, который меняет отображения кода валюты на буквенный или символьный. Также обновлена библиотека @alfalab/utils
> feat(amount): display currency code depending on format

- .changeset/short-forks-wash.md
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-0-color-0-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-0-color-1-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-0-color-2-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-0-color-3-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-0-color-4-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-0-color-5-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-0-color-6-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-1-color-0-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-1-color-1-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-1-color-2-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-1-color-3-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-1-color-4-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-1-color-5-snap.png
- packages/status/src/__image_snapshots__/status-screenshots-views-and-colors-view-1-color-6-snap.png
- packages/status/src/index.module.css
Добавлен текстовый стиль letter-spacing
задача в жире - http://jira.moscow.alfaintra.net/browse/PDS-636?workflowName=PDS%3A+Task+Workflow&stepId=13
> fix(status): added letter-spacing

- .changeset/few-seas-rescue.md
- packages/input/src/index.module.css
Скрыты нативные стрелочки у инпута при type='number'
> fix(input): hidden native arrows

- .changeset/eight-bikes-wave.md
- packages/table/src/components/table-context/index.tsx
- packages/table/src/components/table/Component.tsx
- packages/table/src/components/table/index.module.css
- packages/table/src/components/thead-cell/Component.tsx
- packages/table/src/components/thead-cell/index.module.css
- packages/table/src/docs/description.mdx
Реквест от @mukmyash
Есть необходимость в фиксации заголовков при кроле.
При скроле, заголовки должны прилипать к границе блока
> feat(table): sticky header in table

- .changeset/tall-paws-leave.md
- packages/alert/src/__image_snapshots__/alert-screenshots-with-title-and-closer-title-0-has-closer-0-snap.png
- packages/alert/src/__image_snapshots__/alert-screenshots-with-title-and-closer-title-1-has-closer-0-snap.png
- packages/plate/package.json
- packages/plate/src/Component.tsx
- packages/plate/src/__image_snapshots__/plate-foldable-with-buttons-addons-foldable-1-snap.png
- packages/plate/src/__image_snapshots__/plate-main-props-sprite-snap.png
- packages/plate/src/index.module.css
- packages/plate/tsconfig.json
Удалены иконки подгружаемые с cdn
> fix(plate): delete icon theme

- .changeset/fast-balloons-join.md
- packages/plate/src/index.module.css
Изменен фоновый цвет на light/specialbg/secondary-transparent для компонента Plate в режиме common
> feat(plate): change background color for common mode

- .changeset/fast-tigers-crash.md
- packages/side-panel/src/components/content/Component.desktop.tsx
- packages/side-panel/src/components/footer/Component.desktop.tsx
- packages/side-panel/src/components/header/Component.desktop.tsx
- packages/side-panel/src/docs/Component.stories.mdx
Добавлены в документацию пропсы и их описание для подкомпонентов SidePanel
> docs(side-panel): added in tabs new props

- .changeset/soft-rice-mix.md
- packages/button/src/Component.test.tsx
- packages/button/src/Component.tsx
- packages/button/src/__snapshots__/Component.test.tsx.snap
- packages/button/src/default.module.css
- packages/button/src/index.module.css
- packages/button/src/inverted.module.css
- Добавил хендлер onClick c условием  
`if (disabled || showLoader) {
e.preventDefault();
e.stopPropagation();
}`
- Изменил селектор css c `.component:disabled` на `.component[disabled]`
> fix(button): Исправили disabled в режиме Ссылки

- .changeset/thirty-rockets-dress.md
- package.json
- packages/circular-progress-bar/src/__image_snapshots__/circular-progress-bar-content-color-sprite-snap.png
- packages/circular-progress-bar/src/__image_snapshots__/circular-progress-bar-sprite-snap.png
- packages/typography/src/title-mobile/__image_snapshots__/typography-title-mobile-all-variants-sprite-snap.png
- packages/typography/src/title-mobile/__image_snapshots__/typography-title-mobile-colors-sprite-inverted-snap.png
- packages/typography/src/title-mobile/__image_snapshots__/typography-title-mobile-colors-sprite-snap.png
- packages/typography/src/title-mobile/component.screenshots.test.tsx
- packages/vars/src/typography.css
- yarn.lock
Обновлен пакет ui-primitives и стили для typography
> feat: update UI primitives and typography

- .changeset/perfect-cherries-hug.md
- packages/themes/src/click.ts
- packages/themes/src/corp.ts
- packages/themes/src/intranet.ts
- packages/themes/src/mobile.ts
- packages/themes/src/site.ts
> feat(themes): add js entries

- .storybook/addons/mode-switcher/register.js
- .storybook/addons/mode-switcher/utils.js
- .storybook/addons/theme-switcher/register.js
- .storybook/addons/theme-switcher/utils.js
- .storybook/addons/utils.js
- package.json
- packages/card-image/src/docs/description.mdx
- packages/input-autocomplete/src/docs/description.mdx
- packages/modal/src/docs/description.mdx
- packages/select/src/docs/description.mdx
- packages/utils/mobile.stories.mdx
- yarn.lock
> docs: dark mode & themes in mobile frames

- .storybook/main.js
- package.json
- yarn.lock
При загрузке сторибука должны раскрываться все пункты сайдпанели. Почему-то не всегда работает
> docs: storybook sidepanel expand items

- .changeset/modern-pears-sit.md
- packages/typography/src/component.tsx
- packages/typography/src/text/component.tsx
- packages/typography/src/types.ts
Подправил типизацию для Typography.Text, чтобы можно было передавать ref
> fix(typography): fix typography text type

- .github/workflows/lint-pr.yml
- .github/workflows/update-screenshots.yml
- bin/demo-build.js
- bin/non-existent-css-vars.js
В мае 2023 команда set-output перестанет работать - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: replace set-output command

- packages/pure-cell/src/components/types.ts
Расширен тип (MainElement) для children подкомпонента  PureCell.Main
> fix(pure-cell): fix type MainElement

- .changeset/nasty-ghosts-run.md
- packages/tabs/src/components/primary-tablist/Component.tsx
- packages/tabs/tsconfig.json
- tsconfig.json
Экспортировать PickerButtonDesktop для его корректного использования в отдельных компонентах
> fix(picker-button): add export for PickerButtonDesktop component

- .changeset/happy-parents-exercise.md
- packages/confirmation/src/__image_snapshots__/confirmation-hint-fatal-error-temp-block-screens-sprite-snap.png
- packages/confirmation/src/__snapshots__/Component.test.tsx.snap
- packages/confirmation/src/components/base-confirmation/component.tsx
- packages/confirmation/src/components/base-confirmation/index.module.css
- packages/confirmation/src/components/header/index.module.css
- packages/confirmation/src/components/screens/fatal-error/index.module.css
- packages/confirmation/src/components/screens/hint/component.tsx
- packages/confirmation/src/components/screens/hint/index.module.css
- packages/confirmation/src/components/screens/initial/countdown-section.tsx
- packages/confirmation/src/components/screens/initial/index.module.css
- packages/confirmation/src/components/screens/temp-block/component.tsx
- packages/confirmation/src/components/screens/temp-block/index.module.css
- Исправил верстку failure экрана.
- Поднял специфичность стилей Confirmation, чтобы они всегда перебивали стили других компонентов.
> fix(confirmation): исправил верстку экранов

- packages/select/src/Component.responsive.tsx
- packages/select/src/Component.tsx
- packages/select/src/docs/Component.stories.mdx
- packages/select/src/responsive.ts
Привести к единому виду компоненты с desktop/mobile/responsive версиями, добавить недостающие, где их не хватает
> feat(select): new component select-responsive

- .changeset/popular-comics-hear.md
- packages/code-input/src/component.tsx
- packages/confirmation/src/Component.test.tsx
- packages/confirmation/src/components/base-confirmation/component.tsx
- packages/confirmation/src/components/screens/initial/component.tsx
- packages/confirmation/src/components/screens/initial/countdown-section.tsx
- packages/confirmation/src/docs/Component.stories.mdx
- packages/confirmation/src/docs/description.mdx
- packages/confirmation/src/docs/development.mdx
исправление ошибок + новая демка
> fix(confirmation): reset state when error occurs

- .changeset/early-llamas-punch.md
- packages/calendar-input/src/index.ts
- packages/calendar/src/index.ts
- packages/date-range-input/src/index.ts
- packages/date-time-input/src/index.ts
- packages/input-autocomplete/src/index.ts
- packages/picker-button/src/index.ts
- packages/tooltip/src/docs/Component.stories.mdx
- packages/tooltip/src/index.ts
"export" типов заменен на "export type"
> fix: removed storybook warnings

- .changeset/healthy-news-ring.md
- packages/icon-view/src/__snapshots__/component.test.tsx.snap
- packages/icon-view/src/components/base-shape/component.tsx
Исправлен patternId для imageUrl
> fix(icon-view): fix patternId for imageUrl

- .changeset/stale-toes-train.md
- packages/pure-cell/src/components/text/index.module.css
- packages/pure-cell/src/docs/description.mdx
Исправлено переполнение контейнера PureCell.Text
> fix(pure-cell): fixed overflow PureCell.Text container

- .changeset/stupid-geckos-invite.md
- packages/icon-view/src/__image_snapshots__/icon-view-circle-indicator-snap.png
- packages/icon-view/src/__image_snapshots__/icon-view-super-ellipse-indicator-snap.png
- packages/icon-view/src/components/circle/component.tsx
- packages/icon-view/src/components/super-ellipse/component.tsx
- packages/input/src/__image_snapshots__/input-screenshots-addons-sprite-snap.png
- packages/input/src/__image_snapshots__/input-screenshots-hint-and-error-site-theme-2-snap.png
- packages/input/src/__image_snapshots__/input-screenshots-hint-and-error-site-theme-snap.png
- packages/input/src/__image_snapshots__/input-screenshots-main-props-site-theme-2-snap.png
- packages/select/src/__image_snapshots__/select-interactions-tests-click-open-select-select-one-item-4-snap.png
- packages/select/src/__image_snapshots__/select-multiple-click-snap.png
- packages/select/src/__image_snapshots__/select-optgroup-click-snap.png
> fix(icon-view): fix props size

- .changeset/cool-steaks-bathe.md
- packages/typography/src/title-mobile/index.module.css
- packages/typography/src/title/common.module.css
- packages/typography/src/title/index.module.css
Исправила font-weight для TitleResponsive
> fix(typography): fixed font-weight for TitleResponsive

- packages/pure-cell/src/docs/Component.stories.mdx
- packages/pure-cell/src/docs/description.mdx
- packages/pure-cell/src/docs/development.mdx
Обновлена документация для компонента PureCell
> docs(pure-cell): update docs PureCell

- packages/filter-tag/src/docs/description.mdx
- packages/tabs/src/docs/description.mdx
Обновлена документация для компонента FilterTag
> docs(filter-tag): update docs

- .changeset/shy-months-bake.md
- package.json
- packages/tabs/package.json
- yarn.lock
ПР с фиксом в либе - https://github.com/scroll-into-view/compute-scroll-into-view/pull/784
> fix(tabs): fixed "Cannot read property clientHeight of null" error

- .changeset/young-eggs-peel.md
- packages/textarea/src/index.ts
Пропсы компонента не экспортируются из индексного файла
Пропсы компонента экспортируются из индексного файла
> fix(textarea): экспорт пропсов из индексного файла компонента

- .github/workflows/changesets.yml
- .github/workflows/main.yml
- .github/workflows/non-existent-css-vars.yml
- .github/workflows/screenshots.yml
С данной конфигурацией экшены должны запускаться при выставлении ПРов из форков
> chore: fixed workflow runs

- .changeset/rare-hornets-complain.md
- packages/number-input/package.json
- packages/number-input/src/Component.test.tsx
- packages/number-input/src/Component.tsx
- packages/number-input/src/__snapshots__/Component.test.tsx.snap
- packages/number-input/src/docs/Component.stories.mdx
- packages/number-input/src/docs/description.mdx
- packages/number-input/src/docs/development.mdx
- packages/number-input/src/index.ts
- packages/number-input/tsconfig.json
Добавлен новый компонент NumberInput
> feat(number-input): added new component NumberInput

- packages/bottom-sheet/src/component.tsx
Добавлен проп container, позволяющий указывать контейнер к которому будут добавляться порталы.
> feat(bottom-sheet): add container prop

- .changeset/brave-spies-kiss.md
- packages/vars/src/bundle/site.css
Сайт переходит на палитру bluetint
> feat(vars): update site bundle

- .changeset/afraid-flies-relate.md
Добавил changeset для смерженного ПРа https://github.com/core-ds/core-components/pull/479
> feat(tabs): add changeset for previous tabs package commit

- .changeset/unlucky-lions-vanish.md
- packages/vars/src/Component.stories.mdx
- packages/vars/src/main.css
Добавлен файл main.css с базовыми стилями для проекта
> feat(vars): added new file main.css

- .changeset/six-tools-yawn.md
- package.json
- packages/base-modal/package.json
- yarn.lock
Fix - https://github.com/theKashey/react-focus-lock/issues/123
> fix(base-modal): Update react-focus-lock

- .changeset/rude-owls-battle.md
- packages/bottom-sheet/package.json
- packages/bottom-sheet/src/component.tsx
- packages/select/src/components/base-select-mobile/Component.tsx
- packages/select/src/components/base-select-mobile/virtual-options-list/Component.tsx
- packages/select/src/components/base-select-mobile/virtual-options-list/index.module.css
- packages/select/src/components/base-select-mobile/virtual-options-list/index.ts
- packages/select/src/utils.ts
Пофиксил, но тут явно нужно рефакторить компонент
```jsx
render(() => {
const optionsForVirtualList = React.useMemo(
() =>
new Array(1000).fill().map((_, index) => {
const variableSizeText = `Вы восхитительны! `.repeat(
Math.round(Math.random() * 10),
);
return {
key: index,
content: `${index}. ${variableSizeText}`,
};
}),
[],
);
return <SelectMobile
allowUnselect={true}
options={optionsForVirtualList}
placeholder='Список в модалке'
block={true}
multiple
/>
});
```
```jsx
render(() => {
const optionsForVirtualList = React.useMemo(
() =>
new Array(1000).fill().map((_, index) => {
const variableSizeText = `Вы восхитительны! `.repeat(
Math.round(Math.random() * 10),
);
return {
key: index,
content: `${index}. ${variableSizeText}`,
};
}),
[],
);
return <SelectModalMobile
allowUnselect={true} …
```
> fix(select): virtual options list

- .changeset/tender-lemons-work.md
- packages/button/src/Component.tsx
- packages/button/src/default.module.css
- packages/button/src/docs/component.stories.mdx
- packages/button/src/docs/description.mdx
- packages/button/src/inverted.module.css
- packages/picker-button/src/docs/Component.stories.mdx
Добавлен новый токен для view : 'accent'
> feat(button): added new view

- .changeset/yellow-stingrays-greet.md
- packages/segmented-control/package.json
- packages/segmented-control/src/Component.test.tsx
- packages/segmented-control/src/Component.tsx
- packages/segmented-control/src/__snapshots__/Component.test.tsx.snap
- packages/segmented-control/src/components/index.ts
- packages/segmented-control/src/components/segment/Component.test.tsx
- packages/segmented-control/src/components/segment/Component.tsx
- packages/segmented-control/src/components/segment/__snapshots__/Component.test.tsx.snap
- packages/segmented-control/src/components/segment/index.module.css
- packages/segmented-control/src/components/segment/index.ts
- packages/segmented-control/src/context.ts
- packages/segmented-control/src/docs/Component.stories.mdx
- packages/segmented-control/src/docs/description.mdx
- packages/segmented-control/src/docs/development.mdx
- packages/segmented-control/src/index.module.css
- packages/segmented-control/src/index.ts
- packages/segmented-control/src/typing.ts
- packages/segmented-control/tsconfig.json
Добавление компонента SegmentedControl
> feat(segmented-control): add component

- .changeset/fast-ravens-roll.md
- packages/number-input/src/Component.tsx
- packages/number-input/src/docs/description.mdx
Значение value при сбросе изменено на null
> fix(number-input): reset value changed to null

- .changeset/dry-roses-jog.md
- packages/icon-view/src/components/base-shape/index.module.css
- packages/themes/src/mixins/click.css
- packages/themes/src/mixins/icon-view/click.css
Изменен цвет иконки в теме click
> fix(icon-view): fix icon color in theme click

- .changeset/lemon-cats-do.md
- packages/themes/src/mixins/tag/intranet.css
Сброшена темизация скругления в теме intranet для  shape: rounded
> fix(tag): shape rounded fixed in intranet theme

- .changeset/soft-trees-check.md
- packages/side-panel/src/mobile.module.css
Ограничена максимальная ширина компонента SidePanelMobile
> fix(side-panel): limited max-width SidePanelMobile component

- .changeset/purple-items-tan.md
- packages/modal/src/mobile.module.css
Ограничена максимальная ширина компонента ModalMobile
> fix(modal): limited max-width ModalMobile component

- .storybook/addons/utils.js
- .storybook/manager.js
- .storybook/metrics/config.js
- .storybook/metrics/constant.js
- .storybook/metrics/index.js
- .storybook/metrics/observers.js
- .storybook/metrics/trackEvent.ts
- .storybook/metrics/utils.js
- .storybook/typings/module.d.ts
> feat: added metrics to storybook

- packages/themes/src/mixins/form-control/corp.css
Цвета ошибок в теме corp не соответствуют требованиям
1. Перейти на страницу https://core-ds.github.io/core-components/master/?path=/docs/input--input
2. Выбрать тему corp
3. В разделе Валидация Нажать на кнопку 'Состояние ошибки'
Цвет ошибок #D91D0B | Фактический #EF3124|
Дополнительная информация
> fix(themes): fix error color

- .changeset/clean-singers-nail.md
- packages/button/src/__image_snapshots__/button-views-themes-click-theme-snap.png
- packages/themes/src/mixins/button/click.css
- packages/themes/src/mixins/click.css
Кнопки в состоянии disabled в теме click теперь соответствуют default
> feat(themes): update button in click theme

- .changeset/silly-jobs-play.md
- packages/gallery/src/__image_snapshots__/gallery-interactions-tests-full-screen-snap.png
- packages/gallery/src/__image_snapshots__/gallery-interactions-tests-with-multiple-images-2-snap.png
- packages/gallery/src/__image_snapshots__/gallery-interactions-tests-with-multiple-images-3-snap.png
- packages/gallery/src/__image_snapshots__/gallery-interactions-tests-with-multiple-images-4-snap.png
- packages/gallery/src/__image_snapshots__/gallery-interactions-tests-with-multiple-images-snap.png
- packages/gallery/src/__image_snapshots__/gallery-interactions-tests-with-single-image-snap.png
- packages/gallery/src/components/header-info-block/Component.tsx
- packages/gallery/src/components/header/buttons.tsx
- packages/gallery/src/components/header/index.module.css
- packages/gallery/src/components/image-preview/Component.tsx
- packages/gallery/src/components/image-preview/index.module.css
- packages/gallery/src/components/image-viewer/index.module.css
- packages/gallery/src/components/image-viewer/slide.tsx
- packages/gallery/src/components/navigation-bar/index.module.css
- packages/gallery/src/index.module.css
- packages/vars/src/colors-bluetint.css
- packages/vars/src/colors-indigo.css
- tools/color-mods.json
[Таска](https://jira.moscow.alfaintra.net/browse/PDS-948)
[Макет
](https://www.figma.com/file/OiFlIdSpmFYZ5zsFGWA3TD/Web-%3A%3A-Alfa-Online-Components?node-id=90249%3A453090)
поменял цвета в компоненты галлереи на статичные согласно макету, также исправляется некорректное поведение в темной теме
> feat(gallery): set static colors for gallery

- .changeset/strange-otters-hammer.md
- packages/notification-manager/src/component.test.tsx
- packages/notification-manager/src/component.tsx
Добавил новый необязательный props container
> feat(notification-manager): add new prop container

- .changeset/modern-cherries-dance.md
- .changeset/sharp-moose-jump.md
- .changeset/slow-lemons-push.md
- .changeset/wise-panthers-press.md
- package.json
- packages/backdrop/src/Component.tsx
- packages/backdrop/src/index.module.css
- packages/bottom-sheet/package.json
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-magnetic-areas-test-10-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-magnetic-areas-test-100-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-magnetic-areas-test-50-snap.png
- packages/bottom-sheet/src/__image_snapshots__/bottom-sheet-magnetic-areas-test-negative-20-snap.png
- packages/bottom-sheet/src/__snapshots__/component.test.tsx.snap
- packages/bottom-sheet/src/component.screenshots.test.tsx
- packages/bottom-sheet/src/component.test.tsx
- packages/bottom-sheet/src/component.tsx
- packages/bottom-sheet/src/components/header/Component.tsx
- packages/bottom-sheet/src/components/swipeable-backdrop/Component.tsx
- packages/bottom-sheet/src/docs/description.mdx
- packages/bottom-sheet/src/index.module.css
- packages/bottom-sheet/src/index.ts
- packages/bottom-sheet/src/types.ts
- packages/bottom-sheet/src/utils.ts
- packages/input-autocomplete/src/__snapshots__/Component.test.tsx.snap
- packages/navigation-bar/src/Component.tsx
- packages/navigation-bar/src/types.ts
- packages/notification/package.json
- yarn.lock
Что сделано:
1) Добавлен проп magneticAreas. Принимает список значений, состоящих из чисел, либо строк(процентов, например "10%" ). Значения представляют собой координту Y относительно вьюпорта. Т.е если передали [0, 10%], а высота экрана равна 1000px, то шторка при открытии будет иметь высоту 1000px * 0.1 = 100px. Можно также передавать отрицательные значения - [0, "-10%"]. В этом случае высота шторки при открытии составит 900px. Также допускается передавать больше двух магнитных областей (но не меньше!), например [0, 100, '100%']. Первое и последнее значение списка соответствет минимальной и максимальной возможной высоте соответственно.
2) Добавлен проп initialActiveAreaIndex. По-умолчанию шторка при открытии притянется к последней точке в списке magneticAreas. Собственно этот проп и …
> feat(bottom-sheet): magnetic areas

- .changeset/red-bugs-mate.md
- package.json
- packages/vars/src/typography.css
- yarn.lock
> feat(vars): updated typography

- .changeset/fluffy-oranges-lick.md
- packages/navigation-bar/src/components/closer/index.module.css
- packages/navigation-bar/src/vars.css
- packages/themes/src/mixins/click.css
- packages/themes/src/mixins/navigation-bar/click.css
В теме клик мобильный Closer не соответствует спеке
> feat(navigation-bar): добавление темы click для Closer

- .changeset/soft-mayflies-wink.md
- packages/picker-button/src/__snapshots__/Component.test.tsx.snap
- packages/segmented-control/src/__image_snapshots__/segmented-control-main-props-size-0-shape-0-snap.png
- packages/segmented-control/src/__image_snapshots__/segmented-control-main-props-size-0-shape-1-snap.png
- packages/segmented-control/src/__image_snapshots__/segmented-control-main-props-size-1-shape-0-snap.png
- packages/segmented-control/src/__image_snapshots__/segmented-control-main-props-size-1-shape-1-snap.png
- packages/segmented-control/src/component.screenshots.test.tsx
- packages/segmented-control/src/docs/development.mdx
- packages/segmented-control/src/index.module.css
Исправлен радиус скругления для прямоугольной формы
> fix(segmented-control): fixed rounding radius for rectangular shape

- packages/select/src/docs/Component.stories.mdx
Исправлен фон историй для компонента Select
> docs(select): fix stories background

- .changeset/little-ducks-talk.md
- packages/button/src/__image_snapshots__/button-inverted-views-themes-corp-theme-snap.png
- packages/button/src/__image_snapshots__/button-views-themes-corp-theme-snap.png
- packages/themes/src/mixins/button/corp.css
- packages/themes/src/mixins/corp.css
Изменение вида кнопок accent и primary в corp theme
> chore(themes): corp button view change

- .changeset/four-bottles-wait.md
- packages/checkbox-group/src/__image_snapshots__/checkbox-group-dark-preview-snap.png
- packages/checkbox/src/__image_snapshots__/checkbox-dark-preview-snap.png
- packages/checkbox/src/index.module.css
- packages/radio-group/src/__image_snapshots__/radio-group-dark-preview-snap.png
- packages/radio/src/__image_snapshots__/radio-dark-preview-snap.png
- packages/radio/src/index.module.css
- packages/themes/src/mixins/checkbox/click.css
- packages/themes/src/mixins/checkbox/intranet.css
- packages/themes/src/mixins/checkbox/mobile.css
Изменены токены цвета иконок на static
> fix: changed color markers tokens to static

- .changeset/nine-lobsters-protect.md
- packages/segmented-control/src/components/segment/index.module.css
- packages/segmented-control/src/index.module.css
Для активного таба токены фона и текста изменены на static
> fix(segmented-control): changed color tokens to static

- .changeset/brown-lemons-warn.md
- packages/pure-cell/src/__image_snapshots__/pure-cell-screenshots-direction-horizontal-direction-0-snap.png
- packages/pure-cell/src/components/graphics/index.module.css
- packages/pure-cell/src/components/text/component.tsx
- packages/pure-cell/src/components/text/index.module.css
- packages/pure-cell/src/docs/description.mdx
Изменена дефолтная высота компонента
> fix(pure-cell): changed component height default

- .changeset/breezy-birds-train.md
- packages/switch/src/__image_snapshots__/switch-dark-preview-snap.png
- packages/switch/src/index.module.css
Токен белого цвета изменен на static
> fix(switch): changed color to static

- .changeset/real-cows-provide.md
- .storybook/pages/components-overview/config.ts
- packages/custom-picker-button/package.json
- packages/custom-picker-button/src/Component.desktop.tsx
- packages/custom-picker-button/src/Component.mobile.tsx
- packages/custom-picker-button/src/Component.responsive.tsx
- packages/custom-picker-button/src/Component.test.tsx
- packages/custom-picker-button/src/__image_snapshots__/custom-picker-button-dark-preview-snap.png
- packages/custom-picker-button/src/__image_snapshots__/custom-picker-button-desktop-opened-snap.png
- packages/custom-picker-button/src/__image_snapshots__/custom-picker-button-mobile-opened-snap.png
- packages/custom-picker-button/src/__image_snapshots__/custom-picker-button-preview-snap.png
- packages/custom-picker-button/src/__snapshots__/Component.test.tsx.snap
- packages/custom-picker-button/src/component.screenshots.test.tsx
- packages/custom-picker-button/src/desktop.ts
- packages/custom-picker-button/src/docs/Component.stories.mdx
- packages/custom-picker-button/src/docs/description.mdx
- packages/custom-picker-button/src/docs/development.mdx
- packages/custom-picker-button/src/field/Component.tsx
- packages/custom-picker-button/src/field/index.module.css
- packages/custom-picker-button/src/field/index.ts
- packages/custom-picker-button/src/index.ts
- packages/custom-picker-button/src/mobile.ts
- packages/custom-picker-button/src/responsive.ts
- packages/custom-picker-button/tsconfig.json
- packages/picker-button/src/Component.mobile.tsx
- packages/picker-button/src/Component.tsx
- packages/picker-button/src/docs/Component.stories.mdx
- packages/picker-button/src/docs/development.mdx
- packages/picker-button/src/index.ts
Добавлен новый компонент CustomPickerButton
> feat(custom-picker-button): added new component CustomPickerButton

- .changeset/flat-insects-cough.md
- packages/scrollbar/src/index.module.css
- packages/themes/src/mixins/click.css
- packages/themes/src/mixins/side-panel/click.css
Добавлена темизация АО для компонента SidePanel
> feat(side-panel): added click theming

- .changeset/smart-masks-tan.md
- package.json
- packages/amount-input/package.json
- packages/amount/package.json
- packages/attach/package.json
- packages/confirmation-v1/package.json
- packages/intl-phone-input/package.json
- yarn.lock
обновлено alfalab/data что бы обновить список валют
> feat(amount,amount-input): update data dependency

- .changeset/breezy-sheep-act.md
- packages/dropzone/src/__image_snapshots__/dropzone-dark-preview-snap.png
- packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-0-snap.png
- packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-1-snap.png
- packages/dropzone/src/__image_snapshots__/dropzone-preview-snap.png
- packages/dropzone/src/index.module.css
- packages/themes/src/mixins/dropzone/click.css
радиус скругления изменен на 12px
> fix(dropzone): fillet radius changed to 12px

- .changeset/fast-camels-jam.md
- packages/pure-cell/src/components/main/component.tsx
добавлен пропс className в слот main
> fix(pure-cell): add prop className to main slot

- .changeset/wise-radios-float.md
- packages/calendar-input/src/components/calendar-input/Component.tsx
свойство inputClassName передано компоненту инпута
> fix(calendar-input): passed inputClassName prop to DateInput component

- .changeset/late-poets-lie.md
- .changeset/thick-eagles-yell.md
- packages/calendar/src/components/calendar-mobile/Component.tsx
Необходимо в мобильном приложении отлавливать клик на месяц, чтобы была возможность выбрать месяц, на который нажал пользователь.
При нажатии на тайтл месяца в мобильном приложении должен вызываться колбэк.
> feat(calendar): add onMonthTitleClick

- .changeset/shiny-cameras-refuse.md
- packages/calendar-input/src/components/calendar-input/Component.tsx
- packages/calendar-input/src/docs/description.mdx
- packages/date-range-input/src/components/date-range-input/Component.tsx
- packages/date-range-input/src/docs/description.mdx
- packages/date-time-input/src/components/date-time-input/Component.tsx
Добавлен проп для отключения ввода с клавиатуры в CalendarInput, DateRangeInput, DateTimeInput
> feat: added new props disableUserInput

- .changeset/friendly-comics-attend.md
- packages/icon-view/src/components/base-shape/component.tsx
Добавлен новый пропс shapeClassName для возможности стилизации шейпа. 
Например для перееопределения цвета фона формы через css, когда нет возможности поменять фон через переопределение переменной.
> feat(icon-view): добавлен пропс shapeClassName

- .storybook/addons/theme-switcher/register.js
- .storybook/addons/utils.js
добавлено сохранение выбранной темы в сторибуке
> chore: added saving selected theme storybook

- .changeset/lucky-islands-raise.md
- packages/bottom-sheet/src/component.test.tsx
- packages/bottom-sheet/src/component.tsx
- packages/bottom-sheet/src/components/header/Component.tsx
- packages/bottom-sheet/src/docs/description.mdx
- packages/bottom-sheet/src/index.module.css
- packages/bottom-sheet/src/types.ts
- packages/bottom-sheet/src/utils.ts
- Возможность отслеживания позиции шторки для реализации внешних анимаций
> feat(bottom-sheet): add onOffsetChange handler

- .changeset/blue-bobcats-wash.md
- packages/with-suffix/src/Component.tsx
Были проблемы с рендером AmountInput. Пофиксил коллбэк getPortalContainer в withSuffix
> fix(with-suffix): исправлен коллбэк getPortalContainer

- .changeset/neat-boats-visit.md
- packages/bottom-sheet/src/__snapshots__/component.test.tsx.snap
- packages/bottom-sheet/src/component.tsx
- packages/bottom-sheet/src/index.module.css
- packages/bottom-sheet/src/types.ts
- packages/input-autocomplete/src/__snapshots__/Component.test.tsx.snap
- packages/picker-button/src/__snapshots__/Component.test.tsx.snap
[Пример](https://core-ds.github.io/core-components/feat_bottom_sheet_custom_marker_bfeff4df67f60ea3913b51ecf50d55d0448dd106/?path=/docs/sandbox--docs/code=render(()%20%3D%3E%20%7B%0A%20%20%20%20const%20%5Bopen%2C%20setOpen%5D%20%3D%20React.useState(false)%3B%0A%20%20%20%20const%20handleOpen%20%3D%20()%20%3D%3E%20setOpen(true)%3B%0A%20%20%20%20const%20handleClose%20%3D%20()%20%3D%3E%20setOpen(false)%3B%0A%0A%20%20%20%20const%20commonStyle%20%3D%20%7B%0A%20%20%20%20%20%20%20%20width%3A%20'100%25'%2C%0A%20%20%20%20%20%20%20%20borderRadius%3A%20'8px'%2C%0A%20%20%20%20%20%20%20%20backgroundColor%3A%20'rgba(55%2C%20120%2C%20251%2C%200.1)'%2C%0A%20%20%20%20%20%20%20%20border%3A%20'1px%20dashed%20rgb(55%2C%20120%2C%20251)'%2C%0A%20%20%20%20%20%20%20%20boxSizing%3A%20'border-box'%2C%0A%20%20%20%20% …
> feat(bottom-sheet): new customMarker prop

- .changeset/empty-bikes-wonder.md
- packages/skeleton/src/docs/Component.stories.mdx
- packages/skeleton/src/docs/description.mdx
- packages/skeleton/src/docs/development.mdx
- packages/typography/package.json
- packages/typography/src/docs/description.mdx
- packages/typography/src/hooks/index.ts
- packages/typography/src/hooks/use-skeleton.module.css
- packages/typography/src/hooks/useSkeleton.tsx
- packages/typography/src/text/component.tsx
- packages/typography/src/title/component.tsx
- packages/typography/src/types.ts
- packages/typography/tsconfig.json
```
render(() => {
const [visible, setVisible] = React.useState(false);
return (
<div>
<Button onClick={() => setVisible(p => !p)}>{visible ? 'Показать скелетон' : 'Скрыть скелетон'}</Button>
<Gap size='m'/>
<Typography.Text showSkeleton={visible} skeletonProps={{width: ['100%', '100%', '70%']}} tag='p' view='primary-large'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
</Typography.Text>
<Gap size='m'/>
<Typography.Text showSkeleton={visible} tag='p' view='primary-medium' skeletonProps={{width: ['100%', '100%', …
```
> feat(typography): skeleton for text

- .changeset/stupid-onions-confess.md
- packages/checkbox-group/src/__image_snapshots__/checkbox-group-mobile-direction-0-snap.png
- packages/checkbox-group/src/__image_snapshots__/checkbox-group-mobile-direction-1-snap.png
- packages/checkbox-group/src/component.screenshots.test.tsx
- packages/checkbox-group/src/components/base-checkbox-group/index.module.css
- packages/checkbox-group/src/desktop.module.css
- packages/checkbox-group/src/mobile.module.css
- packages/checkbox-group/src/vars.css
- packages/radio-group/src/__image_snapshots__/radio-group-mobile-direction-0-snap.png
- packages/radio-group/src/__image_snapshots__/radio-group-mobile-direction-1-snap.png
- packages/radio-group/src/component.screenshots.test.tsx
- packages/radio-group/src/components/base-radio-group/index.module.css
- packages/radio-group/src/desktop.module.css
- packages/radio-group/src/mobile.module.css
- packages/radio-group/src/vars.css
исправлены стили для лейбл в радио и чекбокс группах в мобильной версии
> fix: fix styles for label in controls

- .changeset/neat-apricots-exist.md
- packages/radio-group/src/components/base-radio-group/Component.tsx
Есть необходимость прокидывать кастомные стили для самого списка радио элементов
> feat(radio-group): added radioListClassName prop

- .changeset/afraid-clouds-develop.md
- packages/icon-button/src/Component.tsx
> feat(icon-button): add Component to props

- .changeset/silly-panthers-kick.md
- packages/select/src/Component.mobile.tsx
Фиксит баг из-за которого не показывается поиск в одиночном режиме
> fix(select): search in mobile single mode

- package.json
Перед запуском команды, нужно заменить  {userName} на свой доменный логин
> chore: update bb mirror command

- bin/release.js
Поменял местами пуш с публикацией. 
До исправления:
- если вмерджить ПР в мастер во время работающейго Release wotkflow, то новая версия опубликуется в npm, но не залетит в git
После исправления:
- если вмерджить ПР в мастер во время работающейго Release wotkflow, то сначала будет выполнена попытка запушить изменения, если она окажется неудачной, то публикации в npm не произойдет, скрипт упадет
> chore: release improvements

- .changeset/slow-rules-search.md
- packages/amount/src/docs/description.mdx
- packages/amount/src/index.module.css
Добавлено центрирование для контента `rightAddons`.
> fix(amount): add centering for rightAddons

- .changeset/twenty-phones-report.md
- packages/textarea/src/Component.test.tsx
- packages/textarea/src/Component.tsx
Фикс бага с отсутствием фокусной обводки у Textarea
> fix(textarea): useFocus fix

- .changeset/rude-socks-fetch.md
- packages/modal/src/Component.responsive.tsx
- packages/modal/src/components/controls/Component.tsx
- packages/modal/src/components/controls/index.module.css
- packages/modal/src/components/controls/index.ts
- packages/modal/src/components/footer/Component.tsx
- packages/modal/src/components/footer/layout.module.css
- packages/modal/src/desktop/Component.desktop.tsx
- packages/modal/src/docs/Component.stories.mdx
- packages/modal/src/docs/description.mdx
- packages/modal/src/mobile/Component.mobile.tsx
- packages/side-panel/src/Component.responsive.tsx
- packages/side-panel/src/components/controls/Component.tsx
- packages/side-panel/src/components/controls/index.module.css
- packages/side-panel/src/components/controls/index.ts
- packages/side-panel/src/components/footer/Component.mobile.tsx
- packages/side-panel/src/components/footer/layout.module.css
- packages/side-panel/src/components/footer/mobile.module.css
- packages/side-panel/src/desktop/Component.desktop.tsx
- packages/side-panel/src/docs/Component.stories.mdx
- packages/side-panel/src/docs/description.mdx
- packages/side-panel/src/mobile/Component.mobile.tsx
[Пример с модалкой:](https://core-ds.github.io/core-components/feat_modal_controls_69ddcb4df1f2202f76baa420e7f5f387689da0c5/?path=/docs/sandbox--docs/code=render(()%20%3D%3E%20%7B%0A%20%20const%20%5Bopen%2CsetOpen%5D%20%3D%20React.useState(false)%3B%0A%20%20const%20%5BopenMobile%2CsetOpenMobile%5D%20%3D%20React.useState(false)%3B%0A%20%20const%20%5BopenDesktop%2CsetOpenDesktop%5D%20%3D%20React.useState(false)%3B%0A%20%20const%20%5Blayout%2C%20setLayout%5D%20%3D%20React.useState('start')%3B%0A%20%20const%20%5BmobileLayout%2C%20setMobileLayout%5D%20%3D%20React.useState('start')%3B%0A%20%20%0A%20%20const%20toggle%3D()%3D%3EsetOpen(!open)%3B%0A%20%20const%20toggleMobile%3D()%3D%3EsetOpenMobile(!openMobile)%3B%0A%20%20const%20toggleDesktop%3D()%3D%3EsetOpenDesktop(!openDesktop)%3B%0A%20%20%0A%2 …
> feat(modal): added Controls

- .changeset/fair-bears-pump.md
- package.json
- packages/popover/package.json
- packages/popover/src/Component.tsx
- packages/popover/src/index.module.css
- packages/tooltip/src/desktop/Component.desktop.tsx
- yarn.lock
[Пример](https://core-ds.github.io/core-components/fix_popover_arrow_position_66631a7c353e3fb309e296b9d7f377d6aa3696fe/?path=/docs/sandbox--docs/code=%3CTooltipDesktop%0A%20%20%20%20position%3D'right-start'%0A%20%20%20%20trigger%3D'click'%0A%20%20%20%20content%3D%7B%3Cdiv%20style%3D%7B%7B%20width%3A%20241%20%7D%7D%3E%20%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20%D0%BD%D0%B5%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B3%D0%BE%20%D0%B2%D1%81%D0%BF%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE%20%D1%82%D0%B5%D0%BA%D1%81%D1%82%D0%B0.%20%3C%2Fdiv%3E%7D%0A%3E%0A%20%20%20%20%3Cdiv%20style%3D%7B%7B%20height%3A%20200%2C%20border%3A%20'1px%20dashed%20lightgray'%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20%3CTypography.Title%3E%20%D0%A1%D0%B0%D0%BC%D1%8B%D0%B9%20%D1%83%D0%BD%D0%B8%D …
> fix(popover): fixed arrow position

- .changeset/eleven-singers-search.md
- packages/dropzone/src/Component.tsx
https://rc.alfa-bank.net/channel/core-components?msg=QdrH9MLxp8eeBvqmm
> fix(dropzone): added props contentClassName

- .changeset/mean-cats-speak.md
- packages/navigation-bar/src/components/back-arrow-addon/index.module.css
- packages/navigation-bar/src/vars.css
- packages/themes/src/mixins/bottom-sheet/click.css
- packages/themes/src/mixins/navigation-bar/click.css
Обновил темизацию для bottom-sheet в click теме. 
Теперь при скролле у хедера нет бордера и стрелка назад primary цвета
> feat(bottom-sheet): update click theming by new spec

- docs/typography.stories.mdx
- packages/input/src/docs/description.mdx
- packages/plate/src/__image_snapshots__/plate-buttons-addons-left-addons-1-snap.png
- packages/plate/src/__image_snapshots__/plate-dark-preview-snap.png
- packages/plate/src/__image_snapshots__/plate-foldable-with-buttons-addons-foldable-0-snap.png
- packages/plate/src/__image_snapshots__/plate-foldable-with-buttons-addons-foldable-1-snap.png
- packages/plate/src/__image_snapshots__/plate-preview-snap.png
- packages/plate/src/docs/Component.stories.tsx
- packages/plate/src/docs/description.mdx
- packages/pure-cell/src/docs/description.mdx
- packages/steps/src/docs/description.mdx
- packages/toast/src/docs/description.mdx
т.к. Badge теперь deprecated, 
Поменял в  примерах на StatusBadge
> docs(status-badge): replace Badge to StatusBadge in docs

- .changeset/angry-eels-smile.md
- packages/modal/src/__image_snapshots__/click-modal-desktop-2-snap.png
- packages/themes/src/mixins/modal/click.css
в модальном окне обновлены отступы по спецификации для click темы
> feat(modal): update theming by new spec

- .changeset/sharp-queens-press.md
- packages/tooltip/src/default.module.css
Существует потребность менять цвет тултипа
> feat(tooltip): added a background color variable for the tooltip

- .changeset/grumpy-drinks-dream.md
- packages/calendar/src/components/calendar-mobile/Component.tsx
> fix(calendar): fix old dates generation

- .changeset/big-maps-smile.md
- packages/pure-cell/src/component.tsx
- packages/pure-cell/src/index.ts
> fix(pure-cell): added type export PureCellProps

- .changeset/healthy-pumas-melt.md
- packages/calendar/src/components/period-slider/Component.test.tsx
- packages/calendar/src/components/period-slider/Component.tsx
- packages/calendar/src/components/period-slider/__snapshots__/Component.test.tsx.snap
Добавляет возможность изменения текста PeriodSlider для состояния когда ему не переданы даты
> feat(calendar): add period-slider title props

- .changeset/four-penguins-applaud.md
- packages/tabs/src/components/primary-tablist/Component.tsx
- packages/tabs/src/components/scrollable-container/Component.tsx
- packages/tabs/src/components/secondary-tablist/Component.tsx
- packages/tabs/src/components/tabs/Component.test.tsx
- packages/tabs/src/components/tabs/Component.tsx
- packages/tabs/src/typings.ts
Перенес свойство style с корневого тега на заголовок табов.
> refactor(tabs): move stype prop to header

- .storybook/usages.json
Обновление статистики компонентов
> feat: update component usage

- .changeset/lemon-rats-add.md
- packages/navigation-bar/src/Component.tsx
Обернуть компонент NavigationBar в forwardRef
Нужна необходимость зацепиться за рутовую дивку компонента извне
Должно прокидывать рефу наверх
** Ожидаемый  ** | ** Фактический    **|
- OS: MacOS
- Browser: Safari
- Version: 10
- Device: iPhone 6
- OS: iOS 10
- Browser: Chrome
- Version: 65
Дополнительная информация
> feat(navigation-bar): add forwardRef to component | 2

- .changeset/brown-falcons-wave.md
- packages/select/src/components/base-select/Component.tsx
- packages/select/src/components/options-list/Component.tsx
- packages/select/src/components/virtual-options-list/Component.tsx
- packages/select/src/typings.ts
Добавил пропс groupOptionsProp для прокидки дополнительных пропсов в компонент  Optgroup
> feat(select): added new prop groupOptionsProp to SelectProps

- .changeset/strange-vans-own.md
- packages/table/src/components/tsortable-head-cell/Component.tsx
фикс выравнивания текста для TsortableHeadCell
> fix(table): tsortable-head-cell text-align

- .changeset/nasty-years-shop.md
- packages/select/src/components/virtual-options-list/Component.tsx
- packages/select/src/utils.ts
для виртуального списка изменения из https://github.com/core-ds/core-components/pull/1368 оказались не совместимы, сделал дубликат оригинального хука
> fix(select): fixed VirtualOptionsList scroll

- .changeset/slimy-tomatoes-check.md
- packages/typography/src/common.module.css
- packages/typography/src/text/component.tsx
- packages/typography/src/text/index.module.css
- packages/typography/src/title/component.tsx
- packages/typography/src/title/index.module.css
https://rc.alfa-bank.net/channel/core-components-support?msg=6seqMDY7bP69sD6ao
Исправляет моргание текста при использовании пропа showSkeleton
> fix(typography): add opacity

- .changeset/big-zebras-matter.md
- packages/select/src/components/options-list/Component.tsx
> fix(select): revert footer visibility changes

- packages/phone-input/src/Component.test.tsx
отключил тест, который рандомно падает. в будущем нужно разобраться почему
> fix(phone-input): disable test

- .storybook/theming-wizard/config.ts
- .storybook/theming-wizard/questions/index.tsx
> docs: update themization

- .changeset/healthy-ears-shop.md
- packages/textarea/src/index.module.css
> fix(textarea): change specificity

- .changeset/dry-timers-grab.md
- packages/progress-bar/src/Component.tsx
- packages/progress-bar/src/__snapshots__/Component.test.tsx.snap
- packages/progress-bar/src/default.module.css
- packages/progress-bar/src/docs/Component.stories.tsx
- packages/progress-bar/src/index.module.css
- packages/progress-bar/src/inverted.module.css
- packages/progress-bar/src/vars.css
Добавлен inverted цвет для полосы прогресса
> feat(progress-bar): add inverted colors

- .changeset/three-clocks-try.md
- packages/accordion/package.json
- packages/action-button/package.json
- packages/alert/package.json
- packages/amount-input/package.json
- packages/amount/package.json
- packages/attach/package.json
- packages/backdrop/package.json
- packages/badge/package.json
- packages/bank-card/package.json
- packages/base-modal/package.json
- packages/bottom-sheet/package.json
- packages/calendar-input/package.json
- packages/calendar-range/package.json
- packages/calendar-with-skeleton/package.json
- packages/custom-picker-button/package.json
- packages/gallery/package.json
- packages/input-autocomplete/package.json
- packages/input/package.json
- packages/international-phone-input/package.json
- packages/intl-phone-input/package.json
- packages/markdown/package.json
- packages/picker-button/package.json
- packages/plate/package.json
- packages/select-with-tags/package.json
- packages/select/package.json
- packages/universal-date-input/package.json
Добавлены sideEffects: false. Часть 1. (Общий пр застрял - будем кусочками, чтобы полегче https://github.com/core-ds/core-components/pull/1394)
Без изменений
> feat: add sideEffects; part 1

- .changeset/silver-boats-cheer.md
- packages/select/src/components/options-list/Component.tsx
- packages/select/src/typings.ts
Добавил пропс для прокидки класснейма в футер в компонент `OptionsList`
> feat(select): added footerClassName prop to options list

- .changeset/nervous-poets-brush.md
- packages/code-input/package.json
- packages/collapse/package.json
- packages/confirmation/package.json
- packages/date-input/package.json
- packages/filter-tag/package.json
- packages/gap/package.json
- packages/grid/package.json
- packages/link/package.json
- packages/list/package.json
- packages/modal/package.json
- packages/slider/package.json
- packages/space/package.json
- packages/spinner/package.json
- packages/stack/package.json
- packages/status/package.json
- packages/steps/package.json
- packages/tabs/package.json
- packages/tag/package.json
- packages/textarea/package.json
- packages/tooltip/package.json
- packages/underlay/package.json
Добавлен sideEffects в package.json
уже замерженые
part 1 https://github.com/core-ds/core-components/pull/1480
part 2 https://github.com/core-ds/core-components/pull/1486
> feat: add sideeffects; part 3

- .storybook/theming-wizard/answers/keepCssVars/index.tsx
- .storybook/theming-wizard/answers/keepCssVars/utils.ts
> chore: update theme docs

- .changeset/brave-coats-rhyme.md
- packages/comment/package.json
- packages/confirmation-v1/package.json
- packages/custom-button/package.json
- packages/date-range-input/package.json
- packages/date-time-input/package.json
- packages/divider/package.json
- packages/dropzone/package.json
- packages/file-upload-item-v1/package.json
- packages/file-upload-item/package.json
- packages/form-control/package.json
- packages/generic-wrapper/package.json
- packages/hatching-progress-bar/package.json
- packages/icon-button/package.json
- packages/icon-view/package.json
- packages/indicator/package.json
- packages/keyboard-focusable/package.json
- packages/list-header/package.json
- packages/loader/package.json
- packages/masked-input/package.json
- packages/mq/package.json
- packages/navigation-bar-private/package.json
- packages/navigation-bar/package.json
Добавлен sideEffects в package.json. Помогает делать более лучший treeshake
уже замерженые
part 1 https://github.com/core-ds/core-components/pull/1480
part 2 https://github.com/core-ds/core-components/pull/1486
part 3 https://github.com/core-ds/core-components/pull/1491
> feat: add sideeffects; part 4

- .changeset/many-peaches-play.md
- packages/pure-cell/package.json
- packages/pure-cell/src/component.tsx
- packages/pure-cell/src/docs/development.mdx
- packages/pure-cell/src/index.ts
Для лучшего тришейка:
-   Добавлены атомарные экспорты
-   В package.json добавлено sideEffects:false
Без изменений. Дополнена документация: https://core-ds.github.io/core-components/feat_DS_7758_7_5f85a066d7d38a5fd1d28b782a4a04665a569517/?path=/docs/purecell--docs
> feat: pure-sell - add atoms exports

- .changeset/stupid-pets-peel.md
- packages/file-upload-item/src/Component.test.tsx
- packages/file-upload-item/src/Component.tsx
- packages/file-upload-item/src/context/file-upload-item-context.tsx
- packages/file-upload-item/src/docs/development.mdx
- packages/file-upload-item/src/index.ts
- packages/file-upload-item/src/types/file-upload-item-props.ts
- packages/file-upload-item/src/types/status.ts
- packages/file-upload-item/src/utils.ts
добавляет импорты типов пропсов и статусов компонента
https://jira.moscow.alfaintra.net/browse/DS-8488
> feat(file-upload-item): add type export

- .changeset/thin-schools-worry.md
- packages/plate/src/__image_snapshots__/plate-custom-view-and-background-snap.png
- packages/plate/src/__image_snapshots__/plate-custom-view-border-and-background-sprite-snap.png
- packages/plate/src/component.screenshots.test.tsx
- packages/plate/src/components/base-plate/Component.tsx
- packages/plate/src/components/base-plate/index.module.css
- packages/plate/src/docs/Component.stories.tsx
- из документации удален класс который может вводить в заблуждение при использовании компонента на проде
- исправлена передача цвета в border для shape=rect view=custom
https://rc.alfa-bank.net/channel/core-components-support/thread/tfHZ4nyFxdHCYRKXi?msg=tfHZ4nyFxdHCYRKXi
> fix(plate): fix custom view border

- .changeset/wet-frogs-glow.md
- packages/calendar/src/components/calendar-mobile/Component.tsx
- packages/calendar/src/components/calendar-mobile/calendarMonthOnlyView.tsx
- packages/calendar/src/components/calendar-mobile/components/calendar-month-only-view/index.ts
- packages/calendar/src/components/calendar-mobile/index.ts
hotfix 
https://rc.alfa-bank.net/channel/core-components-support?msg=9BNpo3oXhmSqjTYFh
beta
https://www.npmjs.com/package/@alfalab/core-components/v/48.9.0-beta.0
> fix(calendar): change exports

- .changeset/early-needles-chew.md
- packages/tabs/src/components/primary-tablist/Component.tsx
Исправляет расчет размера и положения нижней полосы для primary tab list 
https://jira.moscow.alfaintra.net/browse/DS-8567
> fix(tabs): fix measure bottom line

- .changeset/silly-seas-lie.md
- packages/calendar/src/components/calendar-mobile/calendarMonthOnlyView.tsx
https://rc.alfa-bank.net/channel/core-components-support?msg=63kgZzvwHgGk22ZQ4
> fix(calendar): fix initialMonthIndex

- .changeset/beige-planets-love.md
- packages/vars/src/colors-indigo.css
- tools/update-colors.js
> feat(vars): deprecate colors-indigo.css

- .changeset/many-jobs-watch.md
- packages/slider-input/src/Component.test.tsx
- packages/slider-input/src/Component.tsx
1. Правка blur события
2. derpecate lockLimit
[Удаление будет в мажорке](https://github.com/core-ds/core-components/pull/1542)
> fix(slider-input): fix blur, deprecate lockLimit

- .changeset/fuzzy-pumpkins-deliver.md
- packages/list/src/components/item/Component.tsx
- packages/list/src/docs/Component.stories.mdx
Добавляет дополнительные classNames для List.Item
> feat(list): add additional classNames for list item

- .changeset/fluffy-bags-drop.md
- packages/table/src/components/tbody/Component.tsx
> feat(table): add forward ref to table body

- .changeset/bright-taxis-carry.md
- bin/build-themes.js
в #1501 были добавлены палитры цветов, исключил их из темизаций
> fix(themes): exclude colors palette

- .changeset/swift-ducks-think.md
- packages/typography/src/colors.module.css
- packages/typography/src/colors.ts
> feat(typography): add static-positive color

- .changeset/odd-cars-give.md
- .changeset/thin-laws-peel.md
- packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap
- packages/checkbox/src/Component.screenshots.test.ts
- packages/checkbox/src/Component.tsx
- packages/checkbox/src/__image_snapshots__/checkbox-inverted-colors-2-sprite-snap.png
- packages/checkbox/src/__image_snapshots__/checkbox-inverted-colors-sprite-snap.png
- packages/checkbox/src/__image_snapshots__/checkbox-inverted-hover-state-snap.png
- packages/checkbox/src/__image_snapshots__/checkbox-inverted-pressed-state-snap.png
- packages/checkbox/src/__snapshots__/Component.test.tsx.snap
- packages/checkbox/src/docs/Component.stories.mdx
- packages/checkbox/src/docs/development.mdx
- packages/checkbox/src/styles/default.module.css
- packages/checkbox/src/styles/index.module.css
- packages/checkbox/src/styles/inverted.module.css
- packages/radio-group/src/__snapshots__/Component.test.tsx.snap
- packages/radio/src/Component.tsx
- packages/radio/src/__image_snapshots__/radio-inverted-colors-sprite-snap.png
- packages/radio/src/__image_snapshots__/radio-inverted-hover-state-snap.png
- packages/radio/src/__image_snapshots__/radio-inverted-pressed-state-snap.png
- packages/radio/src/__snapshots__/Component.test.tsx.snap
- packages/radio/src/component.screenshots.test.tsx
- packages/radio/src/docs/Component.stories.mdx
- packages/radio/src/docs/development.mdx
- packages/radio/src/styles/default.module.css
- packages/radio/src/styles/index.module.css
- packages/radio/src/styles/inverted.module.css
Добавлены inverted цвета для checkbox
Добавлены inverted цвета для radio
> feat(checkbox-radio): add inverted colors

- .changeset/warm-crabs-press.md
- packages/modal/src/__image_snapshots__/modal-dark-preview-snap.png
- packages/navigation-bar-private/src/components/back-arrow-addon/index.module.css
- packages/navigation-bar-private/src/components/closer/index.module.css
- packages/side-panel/src/__image_snapshots__/side-panel-dark-preview-snap.png
> feat(navigation-bar-private): fix button colors

- .changeset/big-yaks-collect.md
- packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap
- packages/checkbox/src/Component.test.tsx
- packages/checkbox/src/Component.tsx
Добавил аттрибут name в пропсы input
> fix(input): добавить атрибут name [DS-9443]

- .changeset/wise-baboons-accept.md
- packages/popup-sheet/src/Component.tsx
Исправлено перезатирание класса у closer
> closer navbar classname fix

- .changeset/orange-wolves-drop.md
- packages/icon-view/src/__snapshots__/component.test.tsx.snap
- packages/icon-view/src/component.test.tsx
- packages/icon-view/src/components/base-shape/component.tsx
Измененена реализация компонента IconView так что теперь поддерживается передача анимированных (gif) изображений. Ранее она не поддерживалась из-за использования тега <pattern>
> feat(icon-view): added support for using animated images

- .changeset/slow-cherries-shout.md
- packages/slider/src/Component.tsx
- packages/slider/src/docs/description.mdx
Добавлен пропс snap для точного шага слайдера по range
В рамках задачи DS-10389
> feat(slider): add new snap property for setting certain steps in range(DS-10389)

- .changeset/two-hairs-grab.md
- packages/navigation-bar/src/components/action-icon-addon/Component.tsx
- packages/navigation-bar/src/components/action-text-addon/Component.tsx
Замена импорта button десктоп на мобайл. Компонент только мобильный. Нечего там делать десктопному импорту.
Без изменений
> feat(navigation-bar): change `button` desktop -> mobile import
