- packages/radio-group/src/Component.tsx
- packages/radio-group/src/docs/Component.stories.mdx
- packages/radio-group/src/docs/description.mdx
Нет возможности сбросить выделение дочернего контрола RadioGroup. Данный ПР позволит прокидывать null как value, чтобы компонент RadioGroup сверял value prop c null и checked флаг принимал нужное значение.
Проверил свои изменения локально на последнем Safari.
> feat(radio-group): make radio group value prop nullable

- .storybook/main.js
- package.json
- yarn.lock
Storybook не открывался в OS Windows
Дополнительно удален react-docgen-typescript-loader, так как этот пакет deprecated и не используется в Storybook 6.
> fix: change package paths in storybook webpack config

- packages/file-upload-item/src/index.module.css
В [реквесте](https://github.com/core-ds/core-components/pull/30/) были изменены условия отображения текста ошибки / предупреждения для успешного статуса загрузки файла. В связи с этим пришлось поправить позиционирование размера файла (уезжало вниз к дополнительному тексту).
Было: 
Стало:
> refactor(file-upload-item): change file size positioning

- packages/codemod/package.json
- packages/codemod/src/replace-color-vars/__test__/transform.spec.ts
- packages/codemod/src/replace-color-vars/transform.ts
Некорректно заменялись цвета с модификаторами `shade` | `alpha`
> fix(codemod): fix shade | alpha modificators bug

- packages/list-header/src/__snapshots__/Component.test.tsx.snap
- packages/typography/src/docs/Component.stories.mdx
- packages/typography/src/text/component.test.tsx
- packages/typography/src/text/component.tsx
В PR убран defaultProp weight , так как по-умолчанию для каждого варианта начертания в стилях уже проставлена толщина шрифта.
> fix(typography): removed default weight prop from Typography.Text

- packages/select-with-tags/src/component.tsx
- packages/select-with-tags/src/types.ts
Пресет [useSelectWithApply](https://github.com/core-ds/core-components/tree/master/packages/select/src/presets/useSelectWithApply) не работает с компонентом [SelectWithTags](https://core-ds.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-selectwithtags--select-with-tags)
[Здесь](https://github.com/core-ds/core-components/blob/0befe76680b42a2c9657f0d0755a24c9f8a60f7c/packages/select-with-tags/src/component.tsx#L137) жёстко задается проп optionsListProps, без возможности прокинуть свои пропсы в компонент списка (пришлось удалить emptyListPlaceholder, теперь его нужно передавать в SelectWithTags как проп optionsListProps.emptyPlaceholder)
[Здесь](https://github.com/core-ds/core-components/blob/05b024d07502b3a013270ac15fcc5a3b44773aee/p …
> feat(select-with-tags): add support useSelectWithApply hook

- packages/tooltip/src/component.responsive.tsx
TooltipResponsive не закрывается
1. Перейти на страницу c TooltipResponsive и открыть его
2. Кликнуть на серый фон
Тултип закроется
> fix(tooltip): passing onClose parameter to tooltip component

- bin/build.sh
- bin/export-css-custom-properties-as-js-vars.js
- package.json
- packages/vars/src/Component.stories.mdx
- yarn.lock
Есть необходимость получать доступ к CSS-переменным из JS. Теоретически из JS можно достучаться до кастомных CSS-свойств, но во время сборки переменные заменяются на конечные значения.
Возникла идея сгенерировать файл `index.js`, который будет экспортировать аналоги CSS-переменных из `@alfalab/core-components/vars/index.css`.
Добавлен скрипт `bin/export-css-custom-properties-as-js-vars.js`, который запускается во время сборки и сохраняет файл с JS-переменными в `dist/vars/index.js`.
Не уверен, что все сделано корректно с точки зрения текущей архитектуры сборки. В итоговой директории `dist/vars` создаются поддиректории `modern`, `cssm`, `esm`, которые содержат все то же самое, что и корневая директория (`dist/vars`). Файл с JS-переменными кладется только в `dist/vars`. Вообще насколько …
> feat(vars): export CSS custom properties as JS vars

- packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
- packages/calendar-with-skeleton/src/__snapshots__/Component.test.tsx.snap
- packages/calendar/src/Component.tsx
- packages/calendar/src/__snapshots__/Component.test.tsx.snap
- packages/calendar/src/components/month-year-header/index.module.css
- packages/calendar/src/components/months-table/index.module.css
- packages/calendar/src/components/select-button/index.module.css
- packages/calendar/src/components/years-table/index.module.css
Поднял специфичность css классам кнопок внутри календаря, так как возникали ситуации, когда стили кнопок имели более высокий приоритет, чем стили, которыми внутри календаря их пытались переопределить.
Раньше полагались на последовательность css импортов. Как в итоге оказалось это не всегда и не везде работает.
> fix(calendar): increased button css class specificity

- package.json
- packages/amount-input/package.json
- packages/amount-input/src/Component.test.tsx
- packages/amount-input/src/Component.tsx
- packages/amount-input/src/docs/Component.stories.mdx
- packages/amount-input/src/docs/description.mdx
- packages/amount-input/src/utils/index.ts
- packages/amount/package.json
- packages/attach/package.json
- packages/confirmation/package.json
- packages/filter-tag/package.json
- packages/intl-phone-input/package.json
- yarn.lock
Для компонента AmountInput была добавлена возможность вводить отрицательные значения (с '-' перед значением). Данный функционал закрыт пропой-флагом `positiveOnly` (default - true, т.е. по дефолту нельзя вводить отрицательные значения). 
Также, в ходе разработки (во время изменения регулярки корректного значения инпута) появилась возможность вводить ',' в начало инпута, что затем конвертируется в '0,'. Не уверен, что это не было сделано ранее намеренно, поэтому, если такой функционал не нужен, то это довольно безболезненно можно тут поправить обратно.
> feat(amount-input): added functionality to enter negative values

- packages/select/src/typings.ts
- packages/tooltip/src/component.responsive.tsx
1)Расширил тип emptyPlaceholder компонента OptionList для передачи ReactNode.
2)Прокинул event в хендлеры для открытия и закрытия тултипа
> feat(*): change types for OptionList and add event for handlers to Tooltip

- packages/tooltip/src/component.responsive.tsx
Изменяю медиа запрос, т.к. на планшетах с разрешением 1024 на 600 нужен мобильный компонент тултипа. Получено добро от дизайна(Татьяна Юдина)
> fix(tooltip): change media query for TooltipResponsive

- packages/cdn-icon/src/index.module.css
Компонент CDNIcon выполнен в виде span с инлайонвым отображением (по умолчанию), в связи с чем, он имеет размеры, отличные от содержимого (самой иконки). Это приводит к смещению иконки при использовании. Изменил тип отображения (1 строчка в CSS), чтобы решить проблему.
> feat(cdn-icon): edited icon size fit svg

- packages/side-panel/src/Component.desktop.tsx
- packages/side-panel/src/Component.responsive.tsx
- packages/side-panel/src/components/content/Component.desktop.tsx
- packages/side-panel/src/components/content/Component.tsx
- packages/side-panel/src/components/footer/Component.desktop.tsx
- packages/side-panel/src/components/footer/Component.tsx
- packages/side-panel/src/components/header/Component.desktop.tsx
- packages/side-panel/src/components/header/Component.tsx
Изменила вложенность типизации у SidePanelDesktop и SidePanelResponsive с ( side-panel -> drawer -> base-modal ) и ( side-panel-responsive -> side-panel-desktop && side-panel-modal -> base-modal ) на side-panel -> base-modal 
добавила dataTestId в подкомпоненты Header, Content, Footer
> fix(side-panel): fix ts

- packages/codemod/README.md
- packages/codemod/bin/index.js
- packages/codemod/src/delete-dist/__testfixtures__/transform-with-packages.input.tsx
- packages/codemod/src/delete-dist/__testfixtures__/transform-with-packages.output.tsx
- packages/codemod/src/delete-dist/__testfixtures__/transform.input.tsx
- packages/codemod/src/delete-dist/__testfixtures__/transform.output.tsx
- packages/codemod/src/delete-dist/__tests__/transform.test.ts
- packages/codemod/src/delete-dist/transform.ts
Codemod удаляет '/dist' из импорта
'@alfalab/core-components-button/dist/esm' заменит на '@alfalab/core-components-button/esm'
> feat(codemod): codemode to remove dist from imports

- .storybook/public/global.css
- docs/6.typography.stories.mdx
- packages/cdn-icon/src/Component.tsx
- packages/gallery/src/vars.css
- packages/input/src/default.module.css
- packages/input/src/inverted.module.css
- packages/plate/src/index.module.css
- packages/screenshot-utils/helpers.ts
- packages/select/src/vars.css
- packages/themes/src/mixins/input/site.css
- packages/themes/src/mixins/select/click.css
- Изменил alfabank.gcdn.co на alfabank.servicecdn.ru
BREAKING CHANGE: Добавьте новый домен в список разрешенных 'img-src': `'self' alfabank.servicecdn.ru
data: 'self'`
> feat: Новый cdn alfabank.servicecdn.ru

- bin/purgecss.js
- bin/purgecss.sh
- packages/bank-card/src/index.module.css
1. purgecss по какой-то причине удалял используемые селекторы
2. у нас не работал игнор для отдельных пакетов (не работал для bank-card)
1. Теперь игнор пакетов настраивается в одном месте. Работает для отдельных пакетов и для рута
2. Заставляем purgecss игнорировать ВСЕ селекторы, чтобы он не удалил лишнего. Переменные внутри селекторов все равно могут удалиться, поэтому там где нужно — нужно юзать `/* purgecss ignore */` (bank-card)
> fix: purgecss fixes

- packages/attach/src/Component.tsx
- packages/checkbox/src/Component.tsx
- packages/code-input/src/components/input/component.tsx
- packages/input/src/Component.tsx
- packages/pure-input/src/Component.tsx
- packages/radio/src/Component.tsx
- packages/switch/src/Component.tsx
Обнаружили несовместимость типов @react/types 16 и 18 версии. В интерфейсе InputHTMLAttributes в 16 версии реакта отсутствует свойство enterKeyHint, а forwardRef имеет следующий дженерик - 
`type PropsWithoutRef<P> = P extends any ? ('ref' extends keyof P ? Pick<P, Exclude<keyof P, 'ref'>> : P) : P;`
В итоге, если c 18 версией @react/types указать - `forwardRef<anyType, InputHTMLAttributes<anyType>>()`, то получим в результате тип `ForwardRefExoticComponent<Pick<InputHTMLAttributes>, 'enterKeyHint' | ... etc>`. Все это приводит к тому что свойство enterKeyHint становится обязательным при использовании с 16 версией типов.
Из этой ситуации вижу три выхода - 
1) Обновить версию типов на проекте (что не является хорошим вариантом, к тому же мы поддерживаем 16 реакт).
2) Исключить свойство в …
> fix: omit enterKeyHint prop

- packages/loader/src/index.module.css
Отцентравала лоадер в кнопках, убрав у крайнего элемента отступ
> fix(loader): fix margin-right

- packages/collapse/src/__snapshots__/Component.test.tsx.snap
- packages/confirmation/src/__image_snapshots__/confirmation-code-char-amount-align-sprite-snap.png
- packages/confirmation/src/__snapshots__/Component.test.tsx.snap
- packages/file-upload-item/src/__image_snapshots__/file-upload-item-ellipsis-name-0-upload-date-0-size-0-show-restore-0-snap.png
- packages/file-upload-item/src/__image_snapshots__/file-upload-item-hide-meta-when-show-restore-true-name-0-upload-date-0-size-0-show-restore-0-snap.png
- packages/link/src/Component.tsx
- packages/link/src/__image_snapshots__/link-pseudo-sprite-snap.png
- packages/link/src/__image_snapshots__/link-pseudo-underline-sprite-snap.png
- packages/link/src/__image_snapshots__/link-sprite-snap.png
- packages/link/src/index.module.css
См. issue https://github.com/core-ds/core-components/issues/148
В компоненте Link с пропсом pseudo по дефолту заменяется html-элемент "a" на "button"  с обнуленными стилями
> fix(link): replace component with a button in pseudo mode

- packages/gallery/src/components/image-viewer/component.tsx
- packages/gallery/src/index.module.css
Компонент галлереи отображает слайд высотой 1 пиксель и задний фон с нулевой высотой на ios14<
1. Открыть галерею в сафари на ios14< с мобильного устройства
Картинки в одиночной галерее должны корректно отображаться на мобильных устройствах в safari на ios14<
> fix(gallery): fixed height of swiper on ios 14 and lowest

- packages/attach/src/component.screenshots.test.tsx
- packages/bottom-sheet/src/component.screenshots.test.tsx
- packages/calendar-input/src/component.screenshots.test.tsx
- packages/collapse/src/component.screenshots.test.tsx
- packages/confirmation-v1/src/component.screenshots.test.tsx
- packages/gallery/src/component.screenshots.test.tsx
- packages/input-autocomplete/src/component.screenshots.test.tsx
- packages/intl-phone-input/src/component.screenshots.test.tsx
- packages/keyboard-focusable/src/component.screenshots.test.tsx
- packages/picker-button/src/component.screenshots.test.tsx
- packages/scrollbar/src/Component.screenshots.test.tsx
- packages/select-with-tags/src/component.screenshots.test.tsx
- packages/select/src/component.screenshots.test.tsx
- packages/tooltip/src/component.screenshots.test.tsx
В скриншот тестах при возникновении ошибок, например, не найден указанный селектор на странице, тест завершался успехом из-за того, что ошибки перехватывались в catch.
> chore: fix tests

- .changeset/eighty-seas-visit.md
- packages/calendar-input/src/Component.tsx
fix #276
Кажется, что наличие внешней ошибки не должно влиять на работу компонента
> fix(calendar-input): should pass valid input value if error is set

- .changeset/eighty-yaks-heal.md
- packages/picker-button/src/index.module.css
Удалены разделители опций в выпадающем списке в теме клика
> fix(picker-button): removed option divider

- .changeset/eleven-guests-vanish.md
- packages/modal/package.json
У модалки не было зависимости @alfalab/icons-glyph, а иконка используется в компоненте Modal / Closer
> fix(modal): add icons-glyph dependency

- .changeset/blue-ads-laugh.md
- packages/picker-button/src/field/Component.tsx
- packages/picker-button/src/field/index.module.css
BREAKING CHANGE: При наличии правого аддона, дефолтная иконка кнопки не исчезает
> feat(picker-button): show default button icon if right addon exists

- .changeset/curvy-mails-judge.md
- packages/plate/src/index.module.css
- Исправили max-height контента. Теперь max-height добавляется только раскрываемому(foldable) контенту.
> fix(plate): max-height Только для раскрываемого контента

- .changeset/hip-elephants-decide.md
- packages/picker-button/src/Component.test.tsx
- packages/picker-button/src/Component.tsx
Фактически, компонент ButtonPicker поддерживается список опций в группе, но в интерфейсе это не указано
Исправил тип
[Пример отображения группы в списке](https://core-ds.github.io/core-components/master/?path=/docs/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=const%20options%20%3D%20%5B%7B%0A%20%20%20%20label%3A%20%27%D0%9D%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B%27%2C%0A%20%20%20%20options%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%7B%20key%3A%20%27%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20%D0%B4%D0%BB%D0%B8%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%27%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%7B%20key%3A%20%27%D0%9D%D0%B0%D0%B7%D0%B …
> feat(picker-button): extend options type

- .changeset/stupid-mayflies-give.md
- packages/textarea/src/components/PseudoTextArea.tsx
- packages/textarea/src/index.module.css
Если есть лейбл и нативный скроллбар то размер PseudoTextarea некорректный и мы видим выделение не в том месте где необходимо 
1. Перейти на страницу textarea
2. Добавить пропсы maxLength, showCounter, label, nativeScrollbar.
3 Переполнить textarea
Выделение текста который превышает maxLength
> fix(textarea): некорректный размер PseudoTextarea 

- bin/purgecss.js
- bin/purgecss.sh
- До этого фикса purgeCss для рут пакета запускался в одном потоке и скоуп js файлов для поиска был не ограничен(включал в себя весь dist). 
- После фикса будет параллельно запускаться 10 процессов и скоуп поиска будет ограничен отдельным пакетом(action-button, amount и т.п), а не всем dist.
PurgeCss до фикса отрабатывал примерно за 10 минут, после около 30 сек.
> chore: fix purgecss script

- packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
- packages/calendar-range/src/components/divider/Component.tsx
- packages/calendar-range/src/components/divider/index.module.css
- packages/calendar-range/src/components/divider/index.ts
- packages/calendar-range/src/views/index.module.css
- packages/calendar-range/src/views/popover.tsx
- packages/calendar-range/src/views/static.tsx
Divider в CalendarRange уплывает вверх при наличии label у CalendarInput
1. Добавить label в пропсы inputFromProps и inputToProps
2. Так же указать label внешним = labelView: 'outer'
Ожидается что Divider будет находится по середине с инпутом
Ожидаемый     
Фактический
> fix(calendar-range): correct divider position

- .changeset/ten-shrimps-mix.md
- packages/intl-phone-input/src/__snapshots__/component.test.tsx.snap
- packages/intl-phone-input/src/component.test.tsx
- packages/intl-phone-input/src/component.tsx
- packages/intl-phone-input/src/components/flag-icon/component.tsx
При выключенном пропсе clearableCountryCode можно было нажать ctrl+a и потом удалить весь номер вместе с кодом страны. Теперь код страны остаётся
> fix(intl-phone-input): fix cleare dialcode

- .changeset/wise-peaches-report.md
- packages/steps/src/components/step/Component.tsx
В режиме `interactive={false}` при нажатии на кнопку шага изменяется `activeStep`
> fix(step): interactive button click

- packages/pure-cell/src/index.module.css
Не применяются отступы(gap) для чалдов flex контейнера компонента PureCell на ios13 и ниже. 
https://caniuse.com/?search=flex-gap
1. Открыть https://core-ds.github.io/core-components/master/?path=/docs/components-cells-purecell--pure-cell
на ios13
Отступы остаются на ios13 и ниже.
> feat(pure-cell): replace flex gap to margins for correct work on ios13

- .storybook/addons/mode-switcher/utils.js
- .storybook/blocks/code-editor/github-dark-theme.css
- .storybook/blocks/code-editor/github-light-theme.css
- .storybook/preview.js
- .storybook/public/global.css
К сожалению невозможно точь-в-точь перенести тему из vscode - https://vscodethemes.com/e/github.github-vscode-theme/github-dark-dimmed?language=javascript. Prism.js парсит код все же примитивнее вскода:)
> chore: code editor themes

- .changeset/lovely-pandas-mate.md
- packages/textarea/src/Component.tsx
- packages/textarea/src/__snapshots__/Component.test.tsx.snap
- packages/textarea/src/components/PseudoTextArea.tsx
При передаче пропа value не работает механика переполнения
1. Перейти на страницу [Textarea](https://core-ds.github.io/core-components/master/?path=/docs/components-forms-inputs-textarea--textarea)
2. передать проп maxLength и value превышающее maxLength
Переполненный контент будете выделен
** Ожидаемый  ** | ** Фактический    **|
> fix(textarea): фикс бага переполнения при переданом пропсе value

- .changeset/gentle-students-rescue.md
- packages/intl-phone-input/src/component.tsx
- packages/intl-phone-input/src/utils/preparePasteData.test.ts
- packages/intl-phone-input/src/utils/preparePasteData.ts
Немного изменилась спека, теперь в поле без ру флага при вставке значения без + не нужно подставлять 7 https://www.figma.com/file/cdNnkh2QdxuvYLrBm4cubM/branch/pxLATDZssLAEKvbtCMeQdP/Web-%3A%3A-Core-Default-Components?node-id=65619%3A78962&t=bMoPLGqVd5nsD40K-0
> fix(intl-phone-input): change insert rule

- .storybook/addons/theme-switcher/utils.js
- packages/input/src/__image_snapshots__/input-screenshots-main-props-site-theme-2-snap.png
- packages/select/src/__image_snapshots__/select-interactions-tests-click-open-select-select-one-item-2-snap.png
- packages/select/src/__image_snapshots__/select-interactions-tests-click-open-select-select-one-item-4-snap.png
- packages/select/src/__image_snapshots__/select-multiple-click-snap.png
- packages/select/src/__image_snapshots__/select-optgroup-click-snap.png
При переключении темы в сторибук не подтягивались токены теней (блютинт). Пофиксил.
> chore: include correct css-vars for selected theme

- .changeset/tricky-eggs-study.md
- .github/workflows/main.yml
- .github/workflows/screenshots.yml
- .github/workflows/update-screenshots.yml
- packages/base-modal/src/Component.tsx
- packages/bottom-sheet/src/component.tsx
- packages/modal/src/components/header/Component.tsx
- packages/navigation-bar/src/Component.tsx
- packages/navigation-bar/src/types.ts
- packages/side-panel/src/Component.mobile.tsx
- packages/side-panel/src/components/header/Component.tsx
- packages/side-panel/src/mobile.module.css
В мобильной версии сайд панели не используется обертка в виде Drawer, где проставляется owerflow: auto; для BaseModal и получается что при попытке скролить через рефу componentRef ничего не происходит, потому-что скрол ставится на враппере.
> fix(side-panel): component ref scroll on mobile version

- .changeset/twelve-walls-cover.md
- packages/button/src/default.module.css
- packages/themes/src/mixins/button/click.css
- packages/themes/src/mixins/button/intranet.css
- packages/themes/src/mixins/button/mobile.css
Лоадер в компоненте Button типа primary в темных темах mobile, click, intranet сливался с белым цветом самой кнопки.
Было:
Стало:
> fix(button): fix dark theme button loader color

- .changeset/calm-bulldogs-mix.md
- packages/bottom-sheet/src/components/footer/index.module.css
- packages/bottom-sheet/src/index.module.css
Пример:
```
function Example() {
const [open, setOpen] = React.useState(false);
return (
<div>
<BottomSheet hasCloser onClose={() => setOpen(false)} open={open} actionButton={
<div>
<Button view='primary'>Применить</Button>
</div>
}>
<div style={{height: 1000}}/>
<Plate
view='negative'
title='Компонент плашки'
leftAddons={<Badge view='icon' iconColor='negative' content={<AlertCircleMIcon />} />}
/>
</BottomSheet>
<Button onClick={() => setOpen(true)}>
Нажми на меня
</Button>
</div>
);
}
render(
<Example />
)
```
> fix(bottom-sheet): fixed footer overlaps

- .changeset/warm-feet-eat.md
- packages/side-panel/src/components/content/index.module.css
Пример:
```javascript
function Example() {
const [open, setOpen] = React.useState(false);
return (
<div>
<SidePanelDesktop open={open} onClose={() => setOpen(false)}>
<SidePanelDesktop.Header sticky title='title'/>
<SidePanelDesktop.Content>
<Plate
view='negative'
title='Компонент плашки'
leftAddons={<Badge view='icon' iconColor='negative' content={<AlertCircleMIcon />} />}
/>
<div style={{height: 1000}}/>
<Select options={[{key: '123123'}]}/>
</SidePanelDesktop.Content>
<SidePanelDesktop.Footer sticky>
Footer
</SidePanelDesktop.Footer>
</SidePanelDesktop>
<Button onClick={() => setOpen(true)}>
Нажми на меня
</Button>
</div>
);
}
render(
<Example />
)
```
> fix(side-panel): fixed footer and header overlaps

- .changeset/slimy-mirrors-melt.md
- packages/modal/src/components/content/index.module.css
Пример:
```javascript
function Example() {
const [open, setOpen] = React.useState(false);
return (
<div>
<ModalDesktop open={open} onClose={() => setOpen(false)}>
<ModalDesktop.Header sticky title='title'/>
<ModalDesktop.Content>
<Plate
view='negative'
title='Компонент плашки'
leftAddons={<Badge view='icon' iconColor='negative' content={<AlertCircleMIcon />} />}
/>
<div style={{height: 1000}}/>
</ModalDesktop.Content>
<ModalDesktop.Footer sticky>
Footer
</ModalDesktop.Footer>
</ModalDesktop>
<Button onClick={() => setOpen(true)}>
Нажми на меня
</Button>
</div>
);
}
render(
<Example />
)
```
> fix(modal): fixed footer and header overlaps

- .changeset/hip-plants-deliver.md
- packages/intl-phone-input/src/component.tsx
При value='+79059495743' и defaultCountryIso2='' не форматируется российский номера телефона (пустое значение, так как может быть иностранный номер)
При таких входных параметрах номер телефона должен быть отформатирован
** + 7 905 949-57-43  ** | ** + 7 905 949 57 43     **|
> fix(intl-phone-input): fixed format phone

- .changeset/wicked-monkeys-eat.md
- packages/pure-cell/src/components/addon/component.tsx
- packages/pure-cell/src/components/addon/index.module.css
В компоненте PureCell.Addon по умолчанию verticalAlign = 'top'(lign-self: flex-start). При пробрасывании чалдов в Addon, они смыкаются и прижимаются к верху враппера, без возможности растянуть их на всю высоту враппера
1. Перейти на страницу '...'
2. Нажать на кнопку '...'
Иметь возможность прокинуть проп для растягивания контента Addon на всю высоту контейнера
** Ожидаемый  ** | ** Фактический    **|
- OS: MacOS
- Browser: Safari
- Version: 10
- Device: iPhone 6
- OS: iOS 10
- Browser: Chrome
- Version: 65
Дополнительная информация
> feat(pure-cell): add vertical align auto for Addon

- packages/select/src/components/options-list/Component.tsx
- packages/select/src/components/virtual-options-list/Component.tsx
SelectMobile - при использовании пропа OptionsList при отрисовки options с помощью VirtualOptionsList появляется футер с кнопками, которого не должно быть
1. Перейти на страницу Оплату мобильной связи (/payments/mobile) в мобильном разрешении
2. Нажать на селект Выбор оператора
При нажатии на селект должен появится список доступных операторов без футер
Дополнительная информация
> fix(select-options): fix show footer

- .changeset/six-pillows-juggle.md
- packages/underlay/src/Component.tsx
- packages/underlay/src/docs/Component.stories.mdx
- packages/underlay/src/docs/description.mdx
- packages/underlay/src/index.module.css
- packages/underlay/src/types.ts
- При использовании параметра `borderRadius` равного `xl` - ошибка типа, но компонент выставляет вырный бордерРадиус
- При использовании `borderRadius` равного `l` - скругления не появляетсяются
- Нет возможности настроить overflow без использования классов
- OS: MacOS
- Browser: Safari
- Version: 16.4
> fix: Underlay borderRadius и overflow параметр

- .changeset/nervous-cows-fetch.md
- packages/tag/src/Component.tsx
В пропе onClick у компонента Tag параметры event и payload являются необязательными. В то время как в компоненте CheckboxGroup в пропе onChange они же являются обязательными. Не получается использовать один и тот же обработчик клика для CheckboxGround и Tag. 
Иметь возможность использовать один хэндлер и для CheckboxGround, и для Tag
- не изменено
> feat(tag): make onClick method params required

- .changeset/clean-carrots-judge.md
- packages/steps/src/Component.tsx
- packages/steps/src/components/step/Component.tsx
Добавлена возможность возвращать null для функции checkIsStepCustom, так как это необходимо для применения кастомной иконки к конкретному шагу, иначе иконка будет применяться ко всем шагам.
> fix(steps): make checkIsStepCustom's return value nullable

- .changeset/shaggy-cheetahs-warn.md
- packages/cdn-icon/src/Component.tsx
- packages/cdn-icon/src/index.module.css
При name='flag_abkhazia_m_color' или любой другой цветной иконки с пометкой '_color' компонент возвращал черную иконку.
1. `<CDNIcon name='flag_abkhazia_m_color' />`
При name='flag_abkhazia_m_color' или любой другой цветной иконки с пометкой '_color' компонент должен возвращать цветную иконку.
Ожидаемый  | Фактический
:---------------:|:--------------------
| <img width="377" alt="Screenshot 2023-08-04 at 10 12 20" src="https://github.com/core-ds/core-components/assets/131259332/8de17a50-3069-424a-80a0-2a5a8d498ff9"> | <img width="359" alt="Screenshot 2023-08-04 at 10 13 13" src="https://github.com/core-ds/core-components/assets/131259332/96c6c45e-e167-46fe-bf35-281cd27d681f"> |
> fix(cdn-icon): added color icon support

- .changeset/kind-wombats-guess.md
- packages/textarea/src/Component.tsx
- packages/textarea/src/__snapshots__/Component.test.tsx.snap
- packages/textarea/src/index.module.css
[Было](https://core-ds.github.io/core-components/master/?path=/docs/sandbox--docs/code=function%20Example()%20%7B%0A%20%20%20%20const%20%5Bcount%2C%20setCount%5D%20%3D%20React.useState(0)%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3CTextarea%20value%3D%7B%60%20Lorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipiscing%20elit%2C%20sed%20do%20eiusmod%20tempor%20incididunt%20ut%20labore%20et%20dolore%20magna%20aliqua.%20Nibh%20mauris%20cursus%20mattis%20molestie%20a.%20Fringilla%20phasellus%20faucibus%20scelerisque%20eleifend%20donec.%20Viverra%20tellus%20in%20hac%20habitasse%20platea%20dictumst%20vestibulum.%20Velit%20laoreet%20id%20donec%20ultrices.%20Pulvinar%20sapien%20et%20ligula%20ullamcorper%20malesuada%20proin%20libero% …
> fix(textarea): fixed error with vertical scrollbar and autosize

- rollup.config.mjs
- tools/rollup/core-components-resolver.mjs
Решает проблему с типами, которые ссылаются на packages.
Заменяет импорт import("packages/toast/src).ToastProps --> import("@alfalab/core-components-toast).ToastProps
> chore: typings resolver

- .changeset/spotty-jokes-reply.md
- packages/cdn-icon/src/Component.tsx
- packages/icon-view/src/components/base-shape/index.module.css
[Пример](https://core-ds.github.io/core-components/fix_cdn_icon_full_width_8dfc113889aa84ab936c5fef3c8d46dc0ce92c37/?path=/docs/sandbox--docs/code=render(()%20%3D%3E%20%7B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%20%20%3CSpace%20direction%3D'horizontal'%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%5B'128'%2C%20'80'%2C%20'64'%2C%20'48'%2C%20'40'%2C%20'32'%2C%20'24'%2C%20'20'%5D.map((size)%20%3D%3E%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CSuperEllipse%20size%3D%7Bsize%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CCDNIcon%20name%3D'glyph_debt_m'%20%2F%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FSuperEllipse%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20))%7D%0A%20%20%20%20%20%20%20%20%3C%2FSpace%3E%0A%20%20%20%20)%3B%0A%7D)%3B) - …
> fix(icon-view): fixed CDNIcon size

- .changeset/hot-waves-argue.md
- packages/select/src/components/virtual-options-list/Component.tsx
До этого пересчет высоты происходил только при изменении кол-ва пунктов, теперь проверяем по ключам.
Не смог сейчас воспроизвести баг react-virtual, но помню была проблема в клике, поэтому предлагаю пока не трогать это от греха подальше
```
render(() => {
const [value, setValue] = React.useState('');
const options = value.length % 2 === 0
? [ { key: 'Neptunium', content: (<p style={{height: '42px'}}>Neptunium</p>) }]
: [ { key: 'Plutonium', content: (<p style={{height: '228px'}}>Plutonium</p>) } ];
const handleInput = (event) => {
setValue(event.target.value);
};
return (
<div style={{ width: 320 }}>
<InputAutocompleteDesktop
size='m'
block={true}
options={options}
label='Инпут с автокомплитом'
placeholder='Начните вводить название'
onInput={handleInput}
value={value}
// Remove props …
```
> fix(select): change visible options recalc login in virtual-options-list

- .changeset/thin-ravens-collect.md
- packages/select-with-tags/src/components/tag-list/component.tsx
Исправил баг, из-за которого пересчет кол-ва видимых тэгов срабатывал до построения DOM'а и выдавал неправильный результат. 
Теперь сначала будет срабатывать useEffect, изменяться DOM и только потом будет useLayoutEffect с пересчетом
> fix(select-with-tags): wrong visible elements

- .changeset/wet-rice-accept.md
- packages/amount-input/src/Component.test.tsx
- packages/amount-input/src/Component.tsx
- packages/amount-input/src/utils/index.ts
Необходима возможность выводить мнемонику валюты, а не только символы
> feat(amount-input): add codeFormat prop

- rollup.config.mjs
Отключаем транзитивные импорты, они не должны быть включены с preserveModules флагом (у нас вместо него multiInput плагин, но смысл тот же). https://rollupjs.org/configuration-options/#output-hoisttransitiveimports
Было:
Стало:
> chore: disable hoistTransitiveImports

- .changeset/rich-frogs-brake.md
- .changeset/spicy-planets-rhyme.md
- packages/input-autocomplete/src/Component.test.tsx
- packages/input-autocomplete/src/autocomplete-field/Component.tsx
- packages/input-autocomplete/src/docs/Component.stories.tsx
- packages/input-autocomplete/src/docs/description.mdx
- packages/input-autocomplete/src/mobile/Component.mobile.tsx
- packages/input-autocomplete/src/types.ts
- packages/international-phone-input/src/Component.test.tsx
- packages/international-phone-input/src/components/base-international-phone-input/Component.tsx
- packages/international-phone-input/src/docs/Component.stories.tsx
- packages/international-phone-input/src/docs/description.mdx
- packages/international-phone-input/src/types.ts
- packages/intl-phone-input/src/component.tsx
**Что сделано**
Изменен тип onInput коллбэка с `(event: ChangeEvent | null, payload: {value:string}) => void` на `(value: string) => void`
**Зачем**
Возникают проблемы с event === null
Разработчики часто завязываются именно на первый аргумент коллбэков, игнорируют второй
И если event пришел null, то непонятно какой из этого вывод должен сделать разработчик
Отсюда вытекает подобный код:
```jsx
const handleChange = (event) => {
if (event) {
const { value } = event.target
// do something with value
}
}
```
но это совершенно не равнозначно коду (особенно в случае input-autocomplete)
```jsx
const handleChange = (_, { value }) => {
// do something with value
}
```
что само собой порождает ошибки
> fix(input-autocomplete): changed onInput type

- .changeset/selfish-mails-impress.md
- package.json
- packages/select/package.json
- packages/select/src/components/base-select/Component.tsx
- yarn.lock
Проблема:
- В downshift@8.2.4 (у нас указана ^8.2.2) внесли изменение  https://github.com/downshift-js/downshift/pull/1558, которое ломает controlled мобильный селект, он перестает открываться. Из-за того, что мы используем caret (^) в указании версии,  во всех новых проектах будет установлена последняя 8.x.x версия(8.3.1 на сегодняшний день)
Что сделано:
- Удален костыль для 18 реакта, который возникал из-за сайд эффектов в редьюсере
- menuRef перевешены на обертки модальных сущностей. Внутри downshift есть проверка на то, где произошел клик эвент, если за пределами элемента в menuRef, то селект закрывается. Раньше это также решалось костылем в редьюсере (см.  case useCombobox.stateChangeTypes.InputBlur), который перестал работать в последних версиях downshift
- Для controlled open …
> feat(select): update downshift version

- .changeset/rude-eels-guess.md
- packages/tabs/src/components/primary-tablist/index.module.css
- packages/tabs/src/components/tabs/__snapshots__/Component.test.tsx.snap
- packages/tabs/src/components/title/Component.tsx
Если передать пустой title в tabs и оставить только rightAddon, появляется лишний отступ
1. Перейти на страницу счета с комбо картой
2. посмотреть на комбо табы
Отступа нет
> feat: set margin left 0 when title is false

- .changeset/stale-guests-hang.md
- packages/modal/src/components/header/Component.tsx
Use ModalHeader's own onClose prop. If it doesn't exist, use onClose from Modal component
Не работает пропса onClose в ModalHeader, вместо нее ВСЕГДА используется onClose из ModalContext.
Пропса onClose должна использоваться и иметь приоритет перед onClose из ModalContext
> fix(modal-header): use Header's onClose prop

- .changeset/neat-bikes-rush.md
- packages/bottom-sheet/src/__snapshots__/component.test.tsx.snap
- packages/bottom-sheet/src/component.tsx
- packages/bottom-sheet/src/index.module.css
- packages/input-autocomplete/src/__snapshots__/Component.test.tsx.snap
- packages/picker-button/src/__snapshots__/Component.test.tsx.snap
В компоненте bottom-sheet существует проблема, связанная с address bar. При открытии компонента, кнопки пересекаются с системной областью телефона (home полоска).
Это может приводить к подобному поведению (обратите внимание что address bar располагается сверху)
https://github.com/core-ds/core-components/assets/45999900/c05198ef-f251-4566-bc0b-54d1af56dda4
- Внес исправление, которое добавляет отступ снизу с помощью системной переменной `env()` (для iOS);
- Поправил расчет высоты компонента (для iOS);
- Избавился от дублирования стилей в обертке компонента.
> fix(bottom-sheet): fix safe area

- .changeset/angry-bananas-punch.md
- packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
- packages/calendar/src/Component.test.tsx
- packages/calendar/src/__snapshots__/Component.test.tsx.snap
- packages/calendar/src/components/calendar-mobile/Component.tsx
- packages/calendar/src/components/period-slider/Component.tsx
- packages/calendar/src/components/period-slider/__snapshots__/Component.test.tsx.snap
- packages/calendar/src/desktop/Component.desktop.tsx
- packages/calendar/src/docs/development.mdx
- packages/calendar/src/utils.ts
Добавляю data-test-id к period-slider, чтобы проще подвязываться к стрелкам назад / вперед в автотестах
> feat(calendar): adding data-test-id

- .changeset/rude-beers-talk.md
- packages/dropzone/src/Component.test.tsx
- packages/dropzone/src/Component.tsx
:wave:
BREAKING CHANGE: Изменен тип принимаемого аругумента в обработчике onDrop c FileList на File[]
Имеем такую конструкцию 
Dropzone + Attach
Attach возвращает файлы типа File[], Dropzone -> FileList
Для консистентности перевел тип Dropzone в File[]
Наврядли кто-то использовал методы FileList-а `item` например, но все-же это мажорка
> feat(dropzone): Изменен тип аргумента в onDrop на File[]

- .changeset/brave-paws-lie.md
- packages/calendar/src/components/calendar-mobile/Component.tsx
- packages/calendar/src/desktop/Component.desktop.tsx
- packages/calendar/src/docs/description.mdx
- packages/calendar/src/useRange.ts
- packages/calendar/src/useRangeBehavior.ts
- packages/calendar/src/utils.ts
*Предлагаемые изменения в Calendar*
Т.к. основной запрос был на предоставление более удобного апи для выбора периода в компоненте Calendar, то предлагаю следующие изменения:
1. Не делать мажоррку, либо компонент V2, а только добавить в текущее апи возможность работы с диапазонами дат.
2. Добавить проп `mode?: 'single' | 'range';`
3. По аналогии с UniversalDateInput добавить проп `rangeBehavior` и избавить пользователя от необходимости самому настраивать хуки usePeriod и usePeriodWithReset.
4. Изменить тип `value` на `value?: number | { dateFrom?: number; dateTo?: number };`
5. Изменить тип `onChange` на `(date: number, dateTo?: number) => void`
Кажется, что данных изменений будет достаточно, чтобы решить основные проблемы с текущим компонентом, а также не сломать обратную совместимость и …
> refactor(calendar): range logic

- .changeset/lazy-pots-glow.md
- packages/masked-input/src/Component.tsx
При при обновлении пакетов появилась ошибка ts
> fix(masked-input): export type

- .changeset/healthy-rockets-kiss.md
- packages/phone-input/src/Component.test.tsx
- packages/phone-input/src/Component.tsx
при удалении символов в инпуте в режиме clearableCountryCode каретка перескакивает код города не удаляя его
заполнить phone-input и посимвольно удалить номер
после удаления номера, также должен удалиться код страны
** <img width="406" alt="image" src="https://github.com/user-attachments/assets/009e4e42-6e93-4365-8767-998aa6872ebc">  ** | ** <img width="435" alt="image" src="https://github.com/user-attachments/assets/e5675cb9-11c9-4c00-8ba1-95a6b7ef4e6e">    **|
> fix(phone-input): clearing country code in clearableCountryCode mode

- .changeset/rich-guests-peel.md
- packages/navigation-bar-private/src/types.ts
В заголовок модалки нужно добавить react элемент
Сейчас TS ругается что title должен быть строкой
```
<Modal.Header
title={ (
<TitleView
tag="div"
view={ VIEWS.LARGE }
subtitle="Подзаголовок"
>
Операции по{ NBSP }счёту
</TitleView>
) }
hasCloser={ true }
/>
`
При добавлении React элемента в пропс title, TS не выдается ошибку
** Ожидаемый  ** | ** Фактический    **|
> feat(modal): change type for title from string to ReactNode

- .changeset/purple-pets-whisper.md
- packages/confirmation/src/__snapshots__/Component.test.tsx.snap
- packages/confirmation/src/components/screens/hint/component.tsx
- packages/confirmation/src/types.ts
- packages/confirmation/src/utils.ts
Расширен пропс `texts` компонента `Confirmation`. Добавлены 2 текстовки:
- `domesticPhone` — номер телефона для звонков по России (по дефолту 8 800 200 00 00)
- `internationalPhone` — номер телефона для звонков из-за границы (по дефолту +7 495 78 888 78).
> feat(confirmation): extend 'texts' prop with phone numbers

- .changeset/weak-poems-fail.md
- packages/input/src/components/base-input/Component.tsx
При поднятии версии пакета начали падать тесты с ошибкой InvalidStateError
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange
метод поддерживается только на определенных типах инпута
> fix(input): fix set selection range

- .changeset/happy-moose-grab.md
- packages/pass-code/package.json
- packages/pass-code/src/Component.responsive.tsx
- packages/pass-code/src/desktop/desktop.module.css
- packages/pass-code/src/desktop/index.ts
- packages/pass-code/src/docs/development.mdx
- packages/pass-code/src/index.module.css
- packages/pass-code/src/mobile/index.ts
- packages/pass-code/src/mobile/mobile.module.css
Доработки и оптимизации:
- Добавлены десктоп/мобайл импорты
- Мелкий рефакторинг css - вынесены общие стили в коммон
- Добавлено sideEffects: false
Без изменений
Без изменений
Респонсив: 23,1 kB
д/м версии: 20,8 kB
> feat: pass-code: add desktop / mobile imports

- .changeset/orange-clocks-change.md
- packages/select/src/components/option/Component.responsive.tsx
- packages/select/src/components/option/Component.tsx
- packages/select/src/components/option/desktop/Component.tsx
- packages/select/src/components/option/desktop/index.module.css
- packages/select/src/components/option/index.ts
- packages/select/src/components/option/mobile/Component.tsx
- packages/select/src/components/option/mobile/index.module.css
- packages/select/src/typings.ts
- Добавлен сплит select/option (внутренний компонент)
- В select/shared добавлены OptionDesktop и OptionMobile
Без изменений
> feat(select): split select/option

- .changeset/happy-timers-remember.md
- packages/select/src/presets/useSelectWithApply/hook.tsx
При использовании хука useSelectWithApply на выходе получаем по дефолту проставленный проп allowUnselect: true.  Из-за этого при нажатии на клавишу Backspace в пустой строке поиска снимается выбор с уже добавленных элементов
[ссылка на таску](https://jira.moscow.alfaintra.net/browse/DS-7918)
1. Выбираем несколько пунктов меню
2. Нажимаем применить
3. Снова открываем строку поиска для добавления
4. Кликаем по клавише Backspace
Ранее выбранные  пункты остаются
> fix(select): removed default setting allowUnselect as true in useSelectWithApply

- .changeset/silent-swans-heal.md
- packages/file-upload-item/src/components/content/content.module.css
При использовании опции truncate если текст длинный, а блок, в котором находится компонент ограничен по ширине, то текст начинает расширять компонент и он вылезает за границы
1. Поместить FileUploadItem внутрь блока с ограниченной шириной
2. title должен быть достаточно длинным
3. Применяем проп truncate: true
Текст обрезается и компонент не вылезает за границы блока
> fix(file-upload-item): fix content text truncate

- .changeset/weak-starfishes-leave.md
- packages/picker-button/src/field/Component.tsx
- packages/tabs/src/components/title/Component.tsx
- packages/tabs/src/hooks/use-tabs.tsx
PickerButton и TabsCollapsible при открытии вызывали ошибку передачи в DOM пропсов в camelCase
1. Открыть компонент PickerButton в dev режиме
2. Открыть компонент TabsCollapsible в dev режиме и нажать кнопку еще
В консоли не должно быть ошибок
> fix: remove invalid props from dom

- .github/workflows/screenshots.yml
Изменение версии  actions/upload-artifact@v3 =>  actions/upload-artifact@v4
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> fix: change upload-artifact version

- .changeset/violet-dancers-check.md
- packages/international-phone-input/src/Component.test.tsx
- packages/international-phone-input/src/components/base-international-phone-input/Component.tsx
- packages/international-phone-input/src/types.ts
- packages/international-phone-input/src/utils/index.ts
Требование от НСПК: возможная длина номера тлф до 15 цифр
Добавил пропс для переопределения дефолтного массива countriesData, чтобы по месту использования компонента можно было передать массив в котором уже будет нужная длина номеров телефонов
> fix(intl-phone-input): ability to overwrite country-data

- .changeset/light-penguins-sing.md
- packages/skeleton/src/Component.test.tsx
- packages/skeleton/src/Component.tsx
- packages/skeleton/src/docs/Component.stories.mdx
- packages/skeleton/src/index.module.css
- packages/skeleton/src/vars.css
Добавлен новый проп borderRadius в компонент Skeleton для указания скругления углов. Заложена возможность задания разных значений для каждого угла
[ссылка на таску](https://jira.moscow.alfaintra.net/browse/DS-8489)
> feat(skeleton): new prop borderRadius

- .changeset/tall-elephants-trade.md
- packages/tooltip/src/desktop/Component.desktop.tsx
- packages/tooltip/src/docs/Component.stories.tsx
- packages/tooltip/src/types.ts
Копия https://github.com/core-ds/core-components/pull/1544
> feat(tooltip): add withTransition prop

- .changeset/pink-sloths-suffer.md
- packages/base-modal/src/Component.tsx
- packages/base-modal/src/index.module.css
- packages/bottom-sheet/src/__snapshots__/component.test.tsx.snap
- packages/input-autocomplete/src/__snapshots__/Component.test.tsx.snap
- packages/modal/src/__snapshots__/Component.test.tsx.snap
- packages/modal/src/components/footer/mobile.module.css
- packages/modal/src/components/header/mobile.module.css
- packages/picker-button/src/__snapshots__/Component.test.tsx.snap
- packages/side-panel/src/__snapshots__/Component.test.tsx.snap
- packages/side-panel/src/components/footer/mobile.module.css
- packages/side-panel/src/components/header/mobile.module.css
- packages/side-panel/src/mobile/Component.mobile.tsx
- packages/side-panel/src/mobile/mobile.module.css
Доработка safe-area.
- Если нет header или footer, то отступ добавляется контентной области сверху и снизу соответсвенно;
- Если есть header или footer, то соотвествующие отступы контентной области убираются и формируются непосредственно в header или footer.
Это позволило исправить некоторые визуальные артифакты и проблемы с позиционированием header/footer в состоянии sticky/!sticky
Бета 10.02.25
https://www.npmjs.com/package/@alfalab/core-components/v/48.15.0-beta.0
> feat: safe area improvement

- packages/calendar-range/src/__image_snapshots__/calendar-range-dark-preview-snap.png
- packages/calendar-range/src/__image_snapshots__/calendar-range-off-days-0-snap.png
- packages/calendar-range/src/__image_snapshots__/calendar-range-preview-snap.png
Обновление скриншота. Переодически стреляет во время прогона скриншот тестов. В нем немного изменяется цвет текста в инпуте. Судя по всему тулза считывает такие изменения с погрешностью.
> chore: fix screenshot

- .changeset/big-dingos-roll.md
- packages/circular-progress-bar/package.json
В недавнем обновлении компонента залетела старая версия shared
> fix: fix dependencies

- .changeset/olive-lamps-worry.md
- packages/pass-code/src/Component.tsx
- packages/pass-code/src/desktop/PassCodeDesktop.tsx
- packages/pass-code/src/index.module.css
- packages/pass-code/src/mobile/PassCodeMobile.tsx
В компоненте PassCode типами разрешено свойство `styles`, но оно сломано и не применяется.
Фактически свойство `styles` использовалось для внутреннего механизма применения css-классов для мобильного и десктопного вариантов компонента.
После обсуждения было решено, что свойство `styles` следует убрать (из типов), а для стилизации использовать `className`.
1. Перейти на страницу https://core-ds.github.io/core-components/master/?path=/docs/sandbox--docs
2. Ввести код для воспроизведения:
```
function Example() {
const [value, setValue] = React.useState('');
return (
<div>
<PassCode
styles={{ height: 600, backgroundColor: 'lightBlue' }}
value={value}
onChange={setValue}
maxCodeLength={4}
/>
</div>
);
}
render(
<Example />
)
```
При использовании компонента разработчик не должен иметь …
> Remove styles property from PassCode

- .changeset/tough-wasps-matter.md
- package.json
- packages/amount-input/package.json
- packages/amount/package.json
- packages/attach/package.json
- packages/confirmation-v1/package.json
- packages/intl-phone-input/package.json
- packages/product-cover/package.json
- yarn.lock
Поднята версия `@alfalab/utils` до 1.18.0
> chore: update @alfalab/utils

- .changeset/long-planes-share.md
- package.json
- packages/calendar/package.json
- yarn.lock
В сафари для IOS есть проблема с календарями, не всегда показывается нужный календарь при открытии. 
Виртуализация 2 версии работает не корректно и безконфликтное обновление до 4-ой проблему решает.
https://github.com/user-attachments/assets/3b20b328-ccfa-4efb-96f6-4bca57fb4855
> fix(calendar): fix ios safari behaviour

- .changeset/unlucky-months-care.md
- packages/calendar/src/components/calendar-mobile/calendarMonthOnlyView.tsx
- packages/calendar/src/typings.ts
DS-7885
Исправлено количество отображаемых месяцев при использовании minDate/maxDate пропсов
> fix(calendar): fix minDate/maxDate

- .changeset/two-colts-march.md
- packages/universal-modal/src/Component.test.tsx
- packages/universal-modal/src/components/header/desktop/Component.desktop.tsx
- packages/universal-modal/src/docs/development.mdx
- packages/universal-modal/src/utils/getUniversalModalTestIds.ts
DS-10314
Фикс закрытия universal-modal
Ранее при использовании пропса hasCloser нужно было отдельно в компонент хэдера прокидывать onClose. Теперь onClose будет браться с компонента модалки (как в Modal и SidePanel)
> fix(universal-modal): improve closing (DS-10314)

- .changeset/quiet-experts-march.md
- packages/pure-cell/src/component.tsx
При клике на комопонент и отпускании клавиши мыши за его пределами остается класс active, т.к. событие mouseup, на который висит обработчик для снятия класса, отрабатывает только если мы отпускаем мышку внутри компонента. Полечил довольно простым вариантом - убираю active класс, если мышку уводим за пределы компонента
DS-9053
> fix(pure-cell): fix active state on mouse up outside component

- .changeset/tame-poets-do.md
- packages/select/src/components/base-select/Component.tsx
Разрешен ввод пробелов в textarea
Смоделировать баг можно следующим образом:
[Демо проблемы](https://core-ds.github.io/core-components/master/?path=/docs/sandbox--docs/code=const%20OPTIONS%20%3D%20%5B%0A%20%20%20%20%7B%20key%3A%20'1'%2C%20content%3A%20'One%20Two'%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20'2'%2C%20content%3A%20'Plutonium'%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20'3'%2C%20content%3A%20'Americium'%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20'4'%2C%20content%3A%20'Curium'%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20'5'%2C%20content%3A%20'Berkelium'%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20'6'%2C%20content%3A%20'Californium'%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20'7'%2C%20content%3A%20'Einsteinium'%20%7D%2C%0A%20%20%20%20%7B%20key%3A%20'8'%2C%20content%3A%20'Fermium'%20%7D%2C%0A%5D%3B%0A%0Afunction%2 …
> feat(select): allow space in textarea

- .changeset/smart-ants-repair.md
- packages/shared/src/get-color-var/get-color-var.ts
- packages/shared/src/get-color-var/modify-color.test.ts
- packages/shared/src/get-color-var/modify-color.ts
Миддл может прислать #AARRGGBB формат и функция просто возвращала его. Добавлена функция преобразования такого hex в понятный для веба rgba.
> Добавлена поддержка argb в get-color-var

- .changeset/tasty-falcons-end.md
- packages/international-phone-input/src/types.ts
Кратко сформулируйте суть доработки
В доке и в тс типе есть проп onClear, который вообще не используется в компоненте(обработчик должен добавляться через проп inpurProps). Это вводи пользователей в заблуждение. Теперь этого поля больше нет
- [ x У реквеста осмысленное название feat(...) или fix(...) по conventional commits (https://www.conventionalcommits.org)
> fix(international-phone-input): removed unused prop onClear

- .changeset/hot-avocados-report.md
- packages/base-modal/src/Component.tsx
Исправлен тип TransitionProps на CSSTransitionProps в base-modal.
> fix(base-modal): change TransitionProps type to CSSTransitionProps [DS-9260]

- .changeset/olive-lions-love.md
- packages/calendar/src/components/calendar-mobile/Component.tsx
- packages/calendar/src/components/calendar-mobile/typings.ts
- packages/calendar/src/docs/Component.stories.mdx
DS-10203
Добавлена возможность управлять кнопкой назад для CalendarMobile (пропсы hasBackButton, onBack)
> feat(calendar): add back button to header

- .changeset/healthy-buckets-compare.md
- packages/universal-date-input/src/Component.test.tsx
- packages/universal-date-input/src/components/date-range-input/Component.tsx
в варианте date-range не отрабатывал обработчик onBlur в случае, когда мы используем пикер. Убрал лишнее условие, которое блокировало выполнение хэндлера(в момент события blur setOpen еще не успевает отработать, поэтому никогда не попадаем дальше, при этом с открытым пикером у нас всегда состояние focus, поэтому условие лишнее, да и в других вариантах UniversalDateInput такого условия нет). Не выполнялась также и автокоррекция даты
- [х] Прикреплено изображение было/стало
Раньше(не отрабатывает onBlur и не выполняется autoCorrection)
После
> fix(universal-date-input): fix onBlur handler in date-range-input

- .changeset/wild-experts-sleep.md
- packages/select-with-tags/src/components/tag-list/component.tsx
Исключение возможности проброса onClear через компонент `SelectWithTag` в `BaseFormControl`
> fix(select-with-tags): исключение возможности проброса onClear на div в BaseFormControl

- .changeset/loud-oranges-flow.md
- packages/themes/src/mixins/side-panel/click.css
Вернул для футера сайд панели темы 'click' box-shadow и background целевой реализации
[Макет](https://www.figma.com/design/lGWq8DtnUcSkRasagBuwq6/Web----Core?node-id=208-72557&t=9extBkoFQpHAshZG-0)
> feat(themes): footer side panel unification for click theme

- .changeset/swift-roses-yawn.md
- package.json
- packages/amount-input/package.json
- packages/amount/package.json
- packages/pure-cell/package.json
- yarn.lock
В данным момент, имеется расхождение в символах для китайского юяня в arui-private и core-components.
arui-private использует правильный символ: https://git.moscow.alfaintra.net/projects/EF/repos/arui-private/browse/src/lib/currency-codes/currency-codes.ts#23
https://en.wikipedia.org/wiki/Yen_and_yuan_sign
Тем временем как core-components использует символ казахского алфавита, который берёт из @alfalab/data
https://en.wikipedia.org/wiki/Kazakh_Short_U
Данный ПР обновляет @alfalab/data до последней версии, где эта проблема была исправлена https://git.moscow.alfaintra.net/projects/EF/repos/utils/pull-requests/35/overview
Было:
Стало:
> chore: update @alfalab/data

- .changeset/mighty-impalas-impress.md
- packages/tab-bar/src/index.module.css
DS-11324
Добавлен нижний safe-area отступ для standalone мода
https://www.npmjs.com/package/@alfalab/core-components/v/48.29.0-beta.1
> fix: add safe-area

- .changeset/rotten-forks-help.md
- packages/select/src/components/field/Component.tsx
- packages/select/src/consts.ts
- packages/select/src/typings.ts
- packages/select/src/utils.ts
В select есть параметр valueRenderer, который определяет каким образом будут отрисовываться выбранные элементы. По дефолту вместо valueRenderer прокидывается утилита joinOptions, которая разделяет элементы через ", ". В рамках доработки, добавил возможность прокинуть параметром разделитель (valueSeparator), а не определять у себя целую утилиту valueRenderer под это
> feat(select): Кастомный разделитель

- .changeset/orange-tips-notice.md
- packages/calendar/src/desktop/Component.desktop.tsx
Необходимо дать возможно не скрывать стрелки смены периода при блокировке в календаре.
> feat(calendar): Добавить флаг для слайдера периода "hideDisabledArrows"

- .changeset/ninety-crews-collect.md
- packages/gallery/src/components/header-mobile/Component.tsx
- packages/gallery/src/components/image-viewer/component.tsx
- packages/gallery/src/docs/Component.stories.tsx
Была проблема в том, что при нажатии на кнопку "Поделиться", если изображение имело src из другого источника валился exeption с CORS политикой. Обернул в try, catch для того чтоб не срабатывал return в блоке с navigation.share, где качается изображение, а просто шел шаринг через ссылку без скачивания
> Gallery: улучшена обработка ошибок при шаринге изображений

- .changeset/tame-dancers-grow.md
- packages/tooltip/src/docs/Component.stories.tsx
- packages/tooltip/src/types.ts
Удалён пропс `hasCloser`, который был отмечен как deprecated в core-components@27.x.x. Используйте вместо него `bottomSheetProps.hasCloser`
> refactor(tooltip): get rid of deprecated props

- .changeset/thick-laws-search.md
- packages/circular-progress-bar/src/Component.tsx
- packages/circular-progress-bar/src/types/component-size.ts
- packages/generic-wrapper/src/docs/description.mdx
Удалены буквенные размеры компонента, которые были отмечены как deprecated в core-components@44.x.x
> refactor(circular-progress-bar): get rid of letter sizes

- .changeset/orange-jars-shake.md
- packages/side-panel/src/components/footer/Component.tsx
Исправлен баг, при котором hasFooter не сбрасывался в false при размонтировании компонента
> fix(side-panel): add unmount footer setState

- .changeset/polite-terms-poke.md
- packages/skeleton/src/__image_snapshots__/skeleton-text-align-0-snap.png
- packages/skeleton/src/__image_snapshots__/skeleton-text-align-1-snap.png
- packages/skeleton/src/__image_snapshots__/skeleton-text-align-2-snap.png
- packages/skeleton/src/__image_snapshots__/skeleton-text-rows-0-snap.png
- packages/skeleton/src/__image_snapshots__/skeleton-text-rows-1-snap.png
- packages/skeleton/src/__image_snapshots__/skeleton-text-rows-2-snap.png
- packages/skeleton/src/__image_snapshots__/skeleton-text-width-0-snap.png
- packages/skeleton/src/__image_snapshots__/skeleton-text-width-1-snap.png
- packages/skeleton/src/hooks/use-skeleton/use-skeleton.tsx
DS-12535
Исправлен расчет высоты элементов текстового скелетона. Теперь размер совпадает не с fontSize, а с размером начертания глифов от базовой линии.
Если по какой-то причине canvas не отработает, рассчитается по старой схеме
> fix(skeleton): improve skeleton height measuring
